Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.ssh.insert_key = false
  config.ssh.forward_agent = false
  config.ssh.keep_alive = true
  config.ssh.connect_timeout = 60
  config.vm.boot_timeout = 900

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  nodes = {
    "k8s-master"  => { ip: "192.168.56.10", cpus: 2, memory: 3072, role: "master" },
    "k8s-worker1" => { ip: "192.168.56.11", cpus: 2, memory: 3072, role: "worker-center" },
    "k8s-worker2" => { ip: "192.168.56.12", cpus: 2, memory: 3072, role: "worker-edge" }
  }

  nodes.each do |name, info|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: info[:ip]

      if name == "k8s-master"
        node.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
      elsif name == "k8s-worker1"
        node.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh", auto_correct: true
      elsif name == "k8s-worker2"
        node.vm.network "forwarded_port", guest: 22, host: 2224, id: "ssh", auto_correct: true
      end

      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = info[:memory]
        vb.cpus = info[:cpus]
      end

      node.vm.provision "shell",
        privileged: true,
        inline: <<-SHELL
          sleep 20
        SHELL

      node.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/vagrant/ansible/common.yml"
        ansible.install = true
        ansible.compatibility_mode = "2.0"
        ansible.inventory_path = "/vagrant/ansible/inventory.ini"
        ansible.extra_vars = {
          node_name: name,
          node_ip: info[:ip],
          node_role: info[:role]
        }
      end

      if info[:role] == "master"
        node.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "/vagrant/ansible/master.yml"
          ansible.install = false
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "/vagrant/ansible/inventory.ini"
          ansible.extra_vars = {
            node_name: name,
            node_ip: info[:ip],
            node_role: info[:role]
          }
        end

        node.vm.provision "shell",
          name: "phase2-build",
          run: "never",
          privileged: true,
          inline: <<-SHELL
            export ANSIBLE_FORCE_COLOR=true
            cd /vagrant/ansible
            ansible-playbook \
              -i /vagrant/ansible/inventory.ini \
              /vagrant/ansible/deploy-phase2-build.yml \
              --extra-vars "node_name=#{name} node_ip=#{info[:ip]} node_role=#{info[:role]}"
          SHELL

        node.vm.provision "shell",
          name: "phase2-apply",
          run: "never",
          privileged: true,
          inline: <<-SHELL
            export ANSIBLE_FORCE_COLOR=true
            cd /vagrant/ansible
            ansible-playbook \
              -i /vagrant/ansible/inventory.ini \
              /vagrant/ansible/deploy-phase2-apply.yml \
              --extra-vars "node_name=#{name} node_ip=#{info[:ip]} node_role=#{info[:role]}"
          SHELL
      else
        node.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "/vagrant/ansible/worker.yml"
          ansible.install = false
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "/vagrant/ansible/inventory.ini"
          ansible.extra_vars = {
            node_name: name,
            node_ip: info[:ip],
            node_role: info[:role]
          }
        end

        node.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "/vagrant/ansible/upf.yml"
          ansible.install = false
          ansible.compatibility_mode = "2.0"
          ansible.inventory_path = "/vagrant/ansible/inventory.ini"
          ansible.extra_vars = {
            node_name: name,
            node_ip: info[:ip],
            node_role: info[:role]
          }
        end

        node.vm.provision "shell",
          name: "phase2-load",
          run: "never",
          privileged: true,
          inline: <<-SHELL
            export ANSIBLE_FORCE_COLOR=true
            cd /vagrant/ansible
            ansible-playbook \
              -i /vagrant/ansible/inventory.ini \
              /vagrant/ansible/deploy-phase2-load.yml \
              --extra-vars "node_name=#{name} node_ip=#{info[:ip]} node_role=#{info[:role]}"
          SHELL
      end

      if name == "k8s-worker2"
        node.trigger.after :up do |trigger|
          trigger.name = "auto-deploy-5gc"
          trigger.info = "Worker2 up -> trigger deploy phase 2"
          trigger.run = {
            inline: "cmd /c scripts\\phase2-auto.bat"
          }
        end
      end
    end
  end
end