---
- name: Build and push custom images to local registry on master
  hosts: masters
  become: true
  gather_facts: true
  vars_files:
    - vars.yml
    - vars_helm.yml
  roles:
    - local_registry
    - build_push_registry
