[masters]
k8s-master ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[workers]
k8s-worker1 ansible_connection=local ansible_python_interpreter=/usr/bin/python3
k8s-worker2 ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[k8s_cluster:children]
masters
workers