- name: Prepare all nodes
  hosts: k8s_cluster
  become: true
  gather_facts: true
  roles:
    - common

- name: Init master
  hosts: masters
  become: true
  gather_facts: true
  roles:
    - master_init

- name: Join workers
  hosts: workers
  become: true
  gather_facts: true
  roles:
    - worker_join