---
helm_release_name: etrib5gc
helm_chart_path: /vagrant/helm/etrib5gc
helm_kubeconfig: /etc/kubernetes/admin.conf

local_registry_port: 5000
local_registry_host: "{{ master_ip }}"
local_registry: "{{ local_registry_host }}:{{ local_registry_port }}"

helm_defaults:
  ctrl_service_name: ctrl-svc
  ctrl_cluster_ip: 10.100.100.10
  ctrl_port: 8888

  gateway_service_name: gateway-svc
  gateway_port: 7777
  gateway_location: daejeon

  udr_service_name: udr-mongo
  udr_cluster_ip: 10.100.100.100
  udr_port: 27017
  udr_nodeport: 30001
  udr_image: mongo:latest

  pran_ngap_port: 38412
  pran_sbi_port: 9001
  pran_tac: "001"
  pran_ngap_bind: "0.0.0.0"

  plmn:
    mcc: "208"
    mnc: "93"
    label: "208-93"

  slices:
    - sst: 1
      sd: "010203"
    - sst: 1
      sd: "543210"
