createNamespace: false

global:
  namespace: etri6g
  imageRegistry: 192.168.56.10:5000
  imagePullPolicy: IfNotPresent

  plmn:
    mcc: "208"
    mnc: "93"
    label: "208-93"

  controller:
    serviceName: ctrl-svc
    clusterIP: 10.100.100.10
    port: 8888
    nodePort: 30008

  gateway:
    serviceName: gateway-svc
    clusterIP: 10.100.100.21
    port: 7777
    nodePort: 30007
    externalIp: 192.168.56.10
    location: daejeon

  udr:
    serviceName: udr-mongo
    clusterIP: 10.100.100.100
    port: 27017
    nodePort: 30001
    image: mongo:latest
    pvcSize: 5Gi
    storageClass: gp2

  pran:
    sbiPort: 9001
    ngapPort: 38412
    nodePort: 30500
    tac: "001"
    ngapBind: 0.0.0.0

  serviceDiscovery:
    nsm: nsm-208-93
    udm: udm-208-93
    pcf: pcf-208-93
    ausf: ausf-208-93
    damf: damf-208-93
    amf: amf-208-93
    amf_10_100: amf-208-93-10-100
    amf_10_101: amf-208-93-10-101
    amf_10_102: amf-208-93-10-102
    smf_slice1: smf-208-93-1-010203
    upf: upf-208-93

layout:
  controller: { replicas: 1, site: centre }
  gateway: { replicas: 1, site: centre }
  nsm: { replicas: 1, site: centre }
  udr: { replicas: 1, site: centre }
  udm: { replicas: 1, site: centre }
  ausf: { replicas: 1, site: centre }
  pcf: { replicas: 1, site: centre }
  damf: { replicas: 1, site: centre }
  smf: { replicas: 2, site: centre }
  pran: { replicas: 1, site: edge }
  amf_10_100: { replicas: 2, site: edge }
  amf_10_101: { replicas: 1, site: edge }
  amf_10_102: { replicas: 1, site: edge }
