---
- name: Create apps namespace
  shell: kubectl create namespace {{ apps_namespace }} --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy center app
  command: kubectl apply -f /vagrant/ansible/roles/deploy_apps/files/app-center.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Deploy edge app
  command: kubectl apply -f /vagrant/ansible/roles/deploy_apps/files/app-edge.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Wait for center app
  command: kubectl -n {{ apps_namespace }} rollout status deployment/{{ app_center_name }} --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false

- name: Wait for edge app
  command: kubectl -n {{ apps_namespace }} rollout status deployment/{{ app_edge_name }} --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  changed_when: false