package backend

import (
	"context"
	"encoding/json"
	"etrib5gc/nfs/smf/sm"
	"fmt"
	"github.com/reogac/utils/oam"
	"github.com/urfave/cli/v3"
)

var smfCmds map[string]cli.Command = map[string]cli.Command{
	"list": {
		Name:        "list",
		Usage:       "List sessions",
		Description: "List all Pdu sessions",
		Action: func(ctx context.Context, cmd *cli.Command) error {
			h := ctx.Value("handler").(*OamSmfHandler)
			sessions := h.listSessions()
			if len(sessions) == 0 {
				return fmt.Errorf("No session found")
			} else {
				info, _ := json.MarshalIndent(sessions, "", "  ")
				fmt.Fprintf(cmd.Writer, "%s\n", info)
			}
			return nil
		},
	},
	"release-all": {
		Name:        "release-all",
		Usage:       "Release all sessions",
		Description: "Release all sessions",
		Action: func(ctx context.Context, cmd *cli.Command) error {
			h := ctx.Value("handler").(*OamSmfHandler)
			if h.releaseSessions() {
				fmt.Fprintf(cmd.Writer, "Release all session triggered%s\n")
			} else {
				return fmt.Errorf("Fail to trigger release all sessions")
			}
			return nil
		},
	},

	"view": {
		Name:        "view",
		Usage:       "View a session by its reference",
		Description: "View a session by its reference id generated by SMF",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "id",
				Usage:    "Sm context id generated by SMF",
				Required: true,
			},
		},

		Action: func(ctx context.Context, cmd *cli.Command) error {
			h := ctx.Value("handler").(*OamSmfHandler)
			if s := h.viewSession(cmd.String("id")); s == nil {
				return fmt.Errorf("session not found")
			} else {
				info, _ := json.MarshalIndent(s, "", "  ")
				fmt.Fprintf(cmd.Writer, "%s\n", info)
			}
			return nil
		},
	},
	"release": {
		Name:        "release",
		Usage:       "Release a session by its reference",
		Description: "Release a session by its reference id generated by SMF",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "id",
				Usage:    "Sm context id generated by SMF",
				Required: true,
			},
		},

		Action: func(ctx context.Context, cmd *cli.Command) error {
			h := ctx.Value("handler").(*OamSmfHandler)
			if h.releaseSession(cmd.String("id")) {
				fmt.Fprintf(cmd.Writer, "Release session is triggred\n")
			} else {
				return fmt.Errorf("session not found or not released")
			}
			return nil
		},
	},

	//TODO: define all SMF commands and handler
}

type OamSmfHandler struct {
	nextContext *oam.ServerContext
}

func (b *OamSmfHandler) listSessions() []sm.SessionShortInfo {
	return sm.OamGetSessions()
}

func (b *OamSmfHandler) viewSession(id string) *sm.SessionInfo {
	return sm.OamGetSession(id)
}
func (b *OamSmfHandler) releaseSession(id string) bool {
	return sm.OamReleaseSession(id)
}

func (b *OamSmfHandler) releaseSessions() bool {
	return sm.OamReleaseSessions()
}
