package tunnel

import (
	"etrib5gc/nfs/smf/dataplane"
	"etrib5gc/nfs/smf/topo"
	"fmt"
	"github.com/lvdund/ngap/ies"
	"github.com/reogac/sbi/models"
	"github.com/reogac/utils"
	"github.com/sirupsen/logrus"
	"net"
)

//implement a special GtpFace for link that connect to RAN
type RanFace struct {
	tunnel *Tunnel
}

func (f *RanFace) GetIp() net.IP {
	return f.tunnel.ranIp
}

func (f *RanFace) GetTeid() uint32 {
	return f.tunnel.ranTeid
}

//a node on a data path
type Node struct {
	uplink   *dataplane.Link
	downlink *dataplane.Link
	session  *dataplane.PfcpSession
}

//a data path in a tunnel (PDU session)
type Path struct {
	*logrus.Entry
	id         uint8           //generated by SMF
	pcc        *models.PccRule //PCC rule assigned by PCF to generate the data path
	precedence uint32
	nodes      []*Node  //list of UPF nodes and their links on the path
	qosFlow    *QosFlow //one selected by SMF from Pcc rules
	activated  bool     //is PDRs created?
}

func (t *Tunnel) findUpfPath(tcData []string) (path topo.UpfPath, err error) {
	query := topo.UpfQuery{
		TransportNetworks: t.ranTransportNets,
	}
	found := false
	for _, ref := range tcData {
		if tc, ok := t.trafficControlDataMap[ref]; ok {
			for _, route := range tc.RouteToLocs {
				query.Dnai = route.Dnai
				queryKey := query.String()
				if path, ok = t.cachedPaths[queryKey]; ok {
					found = true
					break
				} else {
					if path, err = topo.GetPath(query); err == nil {
						found = true
						t.cachedPaths[queryKey] = path
						break
					}
				}
			}
		}
		if found {
			break
		}
	}
	if len(tcData) > 0 && !found {
		err = fmt.Errorf("Not path is found for Traffic Control Data")
		return
	}
	if !found {
		var ok bool
		query.Dnai = ""
		queryKey := query.String()
		if path, ok = t.cachedPaths[queryKey]; ok {
			found = true
		} else if path, err = topo.GetPath(query); err == nil {
			t.cachedPaths[queryKey] = path
		}
	}
	return
}

//create a new datapath and add it to the existing list
func (t *Tunnel) createPath(upfPath topo.UpfPath) (path *Path, err error) {
	plen := len(upfPath)
	nodes := make([]*Node, plen)
	var session *dataplane.PfcpSession
	//1. create nodes and bind PFCP sessions
	for i, pathNode := range upfPath {
		//get or create Pfcp session at UPF
		if session, err = t.getPfcpSession(pathNode.Upf); err != nil {
			err = utils.WrapError("Get/Create PFCP session context", err)
			return
		}

		newNode := &Node{
			session: session,
		}

		nodes[i] = newNode
	}
	//2. initialize path with an id
	path = &Path{
		id:    t.pathIdGen.Allocate(),
		nodes: nodes,
	}
	path.Entry = t.WithFields(logrus.Fields{
		"pathId": fmt.Sprintf("%d", path.id),
	})

	//3. chain the nodes
	var remoteIp net.IP
	for i := 0; i < len(nodes); i++ {
		pathNode := upfPath[i]
		node := nodes[i]
		session = node.session

		//create uplink (from RAN or downlink I-UPF)
		if i == 0 { //AN facing UPF
			remoteIp = []byte{}
		} else {
			remoteIp = upfPath[i-1].UlIp
		}
		t.Debugf("Create uplink at node %s for data path %d", pathNode.Upf.Id(), path.id)
		node.uplink = session.GetLink(dataplane.DIRECTION_UPLINK, pathNode.DlIp, remoteIp)

		//downlink (from DN or uplink I-UPF)
		if i == len(nodes)-1 { //anchoring UPF
			remoteIp = []byte{}
		} else {
			remoteIp = upfPath[i+1].DlIp
		}

		t.Debugf("Create downlink at node %s for data path %d", pathNode.Upf.Id(), path.id)
		node.downlink = session.GetLink(dataplane.DIRECTION_DOWNLINK, pathNode.UlIp, remoteIp)

	}

	return
}

func (t *Tunnel) setPcc(p *Path, pcc *models.PccRule) {
	p.pcc = pcc
	if pcc != nil && pcc.Precedence != nil {
		p.precedence = uint32(*pcc.Precedence)
	} else {
		//allocate a precedence for the rule
		p.precedence = t.allocatePrecedence()
	}
}

func (p *Path) createPDRs(t *Tunnel) (err error) {
	if p.activated { //already created
		return
	}
	precedence := uint32(255) //default path
	var flows []models.FlowInformation

	if p.pcc != nil {
		if p.pcc.Precedence != nil {
			precedence = uint32(*p.pcc.Precedence)
		} else {
			//TODO: Precedence management
			precedence = 10
		}
		flows = p.pcc.FlowInfos
	}
	qfi := p.qosFlow.qfi

	var fwdFace dataplane.GtpFace //forwarding face [IP+Teid of the next hop]

	//create PDRs at UPFs on the data path for each flow description
	for i, node := range p.nodes {
		//create uplink PDRs
		if i < len(p.nodes)-1 { //not anchoring UPF
			fwdFace = p.nodes[i+1].uplink
		} else {
			fwdFace = nil
		}
		if err = node.uplink.CreatePDRs(p.id, precedence, qfi, flows, fwdFace); err != nil {
			err = utils.WrapError("Create Uplink PDRs", err)
			return
		}

		if i == 0 { //AN facing UPF
			fwdFace = &RanFace{
				tunnel: t,
			}
		} else {
			fwdFace = p.nodes[i-1].downlink
		}

		//create downlink PDRs
		if err = node.downlink.CreatePDRs(p.id, precedence, qfi, flows, fwdFace); err != nil {
			err = utils.WrapError("Create Downlink PDRs", err)
			return
		}

	}
	p.activated = true
	return
}

//delete all rules from UPF nodes
func (p *Path) deleteRules() {
	p.Debugf("Deactivate path %d", p.id)
	for _, node := range p.nodes {
		node.uplink.DeletePath(p.id)
		node.downlink.DeletePath(p.id)
	}

	p.activated = false
}

//assign a Qos flow for the data path
func (p *Path) setQosFlow(flow *QosFlow) {
	p.qosFlow = flow
	flow.paths[p.id] = p
	p.updateQosFlow() //create QERs for PFCP sessions
}

//create/update QERs for PFCP sessions
func (p *Path) updateQosFlow() {
	for _, node := range p.nodes {
		node.session.UpdateQosFlow(p.qosFlow.qfi, p.qosFlow.qerBuilder)
	}
	return
}

func (p *Path) buildPacketFilters() (filters []PacketFilter) {
	/* TODO: create filters from Flow Descriptions
	for _, flowInfo := range r.FlowInfos {
		if pfs, err := BuildNASPacketFiltersFromFlowInformation(&flowInfo, smCtx); err != nil {
			logger.CtxLog.Warnf("BuildNasQoSRule: Build packet filter fail: %s\n", err)
			continue
		} else {
			pfList = append(pfList, pfs...)
		}
	}
	*/
	filters = []PacketFilter{
		{
			Identifier:    1,
			Direction:     PacketFilterDirectionBidirectional,
			ComponentType: PacketFilterComponentTypeMatchAll,
		}}

	return
}

func (p *Path) buildQosRule(isDefault bool) QosRule {
	p.Debugf("Build Qos rule for path %d", p.id)
	rule := QosRule{
		Identifier:    p.qosFlow.qfi,
		QFI:           p.qosFlow.qfi,
		OperationCode: OperationCodeCreateNewQosRule,
	}
	rule.Precedence = uint8(p.precedence)
	if isDefault {
		rule.PacketFilterList = []PacketFilter{
			{
				Identifier:    1,
				Direction:     PacketFilterDirectionBidirectional,
				ComponentType: PacketFilterComponentTypeMatchAll,
			}}
		rule.DQR = 0x01
	} else {
		rule.PacketFilterList = p.buildPacketFilters()
	}
	return rule
}

func (p *Path) buildQosFlowDesc() QosFlowDesc {
	p.Debugf("Build Qos flow desc for path %d", p.id)
	return p.qosFlow.converter.toNasQosFlowDesc(p.qosFlow.qfi)
}

func (p *Path) buildNgapQosFlowSetupRequestItem() ies.QosFlowSetupRequestItem {
	return p.qosFlow.converter.toNgapQosFlowSetupRequestItem(p.qosFlow.qfi)
}

//check if the first UPF can connect to the gnb's transport network
func (p *Path) isReachable(nets []string) bool {
	return p.nodes[0].session.GetUpf().IsReachable(nets)
}
