package tunnel

import (
	"etrib5gc/nfs/smf/dataplane"
	"etrib5gc/nfs/smf/topo"
	"fmt"
	"github.com/reogac/sbi/models"
	"github.com/reogac/utils"
	"github.com/reogac/utils/idgen"
	"github.com/sirupsen/logrus"
	"math"
	"net"
)

type Tunnel struct {
	*logrus.Entry
	ctx              dataplane.SmContext
	ranTransportNets []string

	paths       map[string]*Path        //all data-paths with PCC rules assigned by PCF
	defaultPath *Path                   //default data path (default Qos flow)
	cachedPaths map[string]topo.UpfPath //cached found UPF paths by query IDs

	ranIp   net.IP
	ranTeid uint32

	sessionRules        map[string]*models.SessionRule //from PCF
	selectedSessionRule string                         //selected session rule (to build default qos flow)

	qfiGen                idgen.Generator[uint8] //qos flow identity generator
	qosFlows              map[string]*QosFlow    //all qos flows indexed by qos ID generated by PCF
	trafficControlDataMap map[string]models.TrafficControlData

	sessions  map[string]*dataplane.PfcpSession //map upf id to its session
	pathIdGen idgen.Generator[uint8]            //path id generator
}

func CreateTunnel(ctx dataplane.SmContext, ranTransportNets []string) *Tunnel {
	t := &Tunnel{
		ctx: ctx,
		Entry: ctx.WithFields(logrus.Fields{
			"mod": "tunnel",
		}),
		ranTransportNets: make([]string, len(ranTransportNets)),
		qfiGen:           idgen.NewGenerator[uint8](2, math.MaxUint8), //1 is reserved for default Qos flow
		paths:            make(map[string]*Path),
		qosFlows:         make(map[string]*QosFlow),
		sessionRules:     make(map[string]*models.SessionRule),
		sessions:         make(map[string]*dataplane.PfcpSession),
		cachedPaths:      make(map[string]topo.UpfPath),
		pathIdGen:        idgen.NewGenerator[uint8](1, math.MaxUint8),
	}
	copy(t.ranTransportNets, ranTransportNets)
	return t
}

//get an existing session at a Upf or create a new one for the tunnel
func (t *Tunnel) getPfcpSession(upf *dataplane.Upf) (session *dataplane.PfcpSession, err error) {
	upfId := upf.Id()
	if s, ok := t.sessions[upfId]; ok {
		session = s
		return
	}
	if session, err = upf.CreateSession(t.ctx.(dataplane.SmContext)); err == nil {
		t.sessions[upfId] = session
	}
	return
}

//check if the tunnel can conntect to a gnB (in case of path switch)
func (t *Tunnel) IsConnectedToRan(nets []string) bool {
	//all data paths much be reachable
	for _, p := range t.getAllPaths() {
		if !p.isReachable(nets) {
			return false
		}
	}
	return true
}

//disconnect from RAN
func (t *Tunnel) DisconnectRan() (err error) {
	sessions := make(map[string]*dataplane.PfcpSession)
	for _, p := range t.getAllPaths() {
		anNode := p.nodes[0]
		anNode.downlink.DeactivateFAR(p.id)
		sessions[anNode.session.GetUpfId()] = anNode.session
	}
	if err = t.updateUPFs(sessions); err != nil {
		err = utils.WrapError("Update sessions at UPFs", err)
	}
	return
}

// Once receive IP and TEID from RAN, update the forwarding rule for the first
// UPF so that it can forward downlink packets toward gnB
func (t *Tunnel) UpdateRanInfo(ip net.IP, teid uint32) (err error) {

	t.ranIp = ip
	t.ranTeid = teid

	sessions := make(map[string]*dataplane.PfcpSession)
	for _, path := range t.getAllPaths() {
		//the first UPF (connecting to gnB)
		anNode := path.nodes[0] //must not be nil
		link := anNode.downlink
		link.UpdateFAR(path.id, ip, teid)
		sessions[anNode.session.GetUpfId()] = anNode.session
	}
	if err = t.updateUPFs(sessions); err != nil {
		err = utils.WrapError("Update sessions at UPFs", err)
	} else {
		t.Infof("Tunnel is updated with gnB information [ip = %s, teid = %d]", ip.String(), teid)
	}
	return
}

func (t *Tunnel) getAllPaths() (all []*Path) {
	hasDefault := false
	for _, p := range t.paths {
		hasDefault = t.isDefaultPath(p)
		all = append(all, p)
	}
	if !hasDefault && t.defaultPath != nil {
		all = append(all, t.defaultPath)
	}
	return
}

func (t *Tunnel) Release() (err error) {
	//1. remove all rules from UPFs
	for _, path := range t.getAllPaths() {
		path.deleteRules()
	}
	//2. ask UPFs to release sessions
	for _, s := range t.sessions {
		s.Release()
	}
	return
}

func (t *Tunnel) SuspendGnb() (err error) {
	return fmt.Errorf("Ran supension not implemented")
}

func (t *Tunnel) createDefaultPath() (err error) {
	if t.defaultPath != nil {
		return
	}
	//check if we can pick one of the existing path as default
	for _, path := range t.paths {
		if canBeDefault(path.pcc) {
			t.Infof("Datapath %d is used as default path", path.id)
			t.setDefaultPath(path)
			return
		}
	}
	var upfPath topo.UpfPath
	if upfPath, err = t.findUpfPath(nil); err != nil { //find path without traffic control data
		err = utils.WrapError("Find Upf Path to create a default path", err)
		return
	}

	var path *Path
	if path, err = t.createPath(upfPath); err != nil {
		err = utils.WrapError("Create default datapath", err)
		return
	}
	t.Infof("Create datapath %d to used as default path", path.id)
	t.setDefaultPath(path)
	return
}

func (t *Tunnel) setDefaultPath(p *Path) {
	p.precedence = 255 //set default precedence
	t.defaultPath = p
}

func (t *Tunnel) allocatePrecedence() uint32 {
	//TODO: find a way to allocate precedence
	return 10
}

func (t *Tunnel) freePrecedence(precedence uint32) {
	//NOTE: do nothing now
}

func (t *Tunnel) HandleSmPolicyDecision(pol *models.SmPolicyDecision) (err error) {

	updateDefaultQos := t.defaultPath == nil //need to add/update default Qos

	//handle TrafficControlData
	for id, dat := range pol.TraffContDecs {
		t.Tracef("Handle Traffic control description %s", id)
		if dat == nil { //to delete
			delete(t.trafficControlDataMap, id)
		} else { //update or create new TrafficControlData
			dat.TcId = id
			t.trafficControlDataMap[dat.TcId] = *dat
		}
	}

	//handle PccRules
	for id, rule := range pol.PccRules {
		t.Tracef("Handle Pcc rule %s", id)
		if rule == nil {
			t.deletePccRule(id)
		} else {
			//create a new datapath or update an existing one
			rule.PccRuleId = id
			t.updatePccRule(rule)
		}
	}

	//make sure to have a default datapath
	if err = t.createDefaultPath(); err != nil {
		err = utils.WrapError("Pick/create a default path", err)
		return
	}

	//handle Session Rules
	for id, rule := range pol.SessRules {
		t.Tracef("Handle session rule %s", id)
		if rule == nil { //delete a session rule
			if _, ok := t.sessionRules[id]; ok {
				delete(t.sessionRules, id)
				if id == t.selectedSessionRule { //if current selected session rule is delete
					updateDefaultQos = true
				}
			}
		} else { //update or create new session rule
			rule.SessRuleId = id
			if _, ok := t.sessionRules[id]; ok { //rule existed
				t.sessionRules[rule.SessRuleId] = rule
				//if updated session rule is the selected one, need to update
				//default Qos for the UPFs on the default path
				if id == t.selectedSessionRule {
					updateDefaultQos = true
				}
			} else { //add the new session rule
				t.sessionRules[id] = rule
				//pick a selected session rule
				if len(t.selectedSessionRule) == 0 {
					t.selectedSessionRule = id
				}
			}
		}
	}

	if updateDefaultQos {
		t.updateDefaultQos() //create or update QERs for default path
	}

	//3. handle QosData
	for id, dat := range pol.QosDecs {
		t.Tracef("Handle Qos description %s", id)
		if dat == nil { //to delete
			t.deleteQosFlow(id)
		} else { //update or create new QosFlow
			dat.QosId = id
			t.updateQosFlow(dat)
		}
	}

	//4. assign Qos flow for data path
	for id, rule := range pol.PccRules {
		if path, ok := t.paths[id]; ok && path.qosFlow == nil {
			if qosFlow := t.pickQosFlow(rule); qosFlow != nil {
				path.setQosFlow(qosFlow)
			} else {
				//TODO: cancel transactions
				err = fmt.Errorf("Pcc %s has no Qos flow", id)
				return
			}
		}
	}

	//5. create PDRs and related rules for new created data paths
	if err = t.defaultPath.createPDRs(t); err != nil {
		err = utils.WrapError("Create PDRs for default data path", err)
		//TODO: cancel transactions
		return
	}

	for _, path := range t.paths {
		if err = path.createPDRs(t); err != nil {
			err = utils.WrapError("Create PDRs for data path", err)
			//TODO: cancel transactions
			return
		}
	}

	//ask UPFs to execute all pending transactions
	if err = t.updateUPFs(nil); err != nil {
		err = utils.WrapError("Update sessions at UPFs", err)
	}
	return
}

func (t *Tunnel) updateDefaultQos() {
	t.Tracef("Update default Qos flow")
	var rule *models.SessionRule
	if len(t.selectedSessionRule) > 0 {
		rule, _ = t.sessionRules[t.selectedSessionRule]
	}
	//update default Qos Flow for the default Path
	t.defaultPath.setQosFlow(newDefaultQosFlow(rule))
}

func (t *Tunnel) deletePccRule(id string) {
	if path, ok := t.paths[id]; ok {
		delete(t.paths, id)
		t.freePrecedence(path.precedence)
		if !t.isDefaultPath(path) { //don't remove default path
			path.deleteRules() //delete PDRs/FAR
			t.pathIdGen.Free(path.id)
		} //fire an warning if it is the default path
	}
}

func (t *Tunnel) isDefaultPath(p *Path) bool {
	if t != nil && t.defaultPath != nil {
		return p.id == t.defaultPath.id

	}
	return false
}

func (t *Tunnel) updatePccRule(rule *models.PccRule) (err error) {
	if _, ok := t.paths[rule.PccRuleId]; ok {
		//update an existing path
		//TODO: simplest solution is to delete this path then create a new one
		err = fmt.Errorf("Update existing PccRule not handled yet")
		return
	} else {
		//create a new data path
		var upfPath topo.UpfPath
		//1. Find Upf Path
		if upfPath, err = t.findUpfPath(rule.RefTcData); err != nil {
			err = utils.WrapError("Find UPF path", err)
			return
		}

		var path *Path
		//2. create data path
		if path, err = t.createPath(upfPath); err != nil {
			err = utils.WrapError("Build UPF path", err)
		}
		t.setPcc(path, rule)
		t.paths[rule.PccRuleId] = path

		t.Infof("Data path %d is created for Pcc rule %s", path.id, rule.PccRuleId)
	}
	return
}

//send PfcpSessionEstablishment/PfcpSessionModification toward UPFs in the
//datapaths
func (t *Tunnel) updateUPFs(sessions map[string]*dataplane.PfcpSession) (err error) {
	t.Tracef("Update Pfcp sessions")
	if len(sessions) == 0 { //if the list is empty, take all sessions
		sessions = t.sessions
	}

	l := len(sessions)
	errCh := make(chan error, l)

	worker := dataplane.Worker()
	for _, s := range sessions {
		worker.Go(func() {
			errCh <- s.Update()
		})
	}

	for i := 0; i < l; i++ {
		if err = <-errCh; err != nil {
			err = utils.WrapError("Update pfcp sesion [first encounter error]", err)
			return
		}
	}

	return
}
