package topo

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math/rand"
	"net"
	"strings"

	"etrib5gc/common"
	"etrib5gc/mesh"
	"etrib5gc/nfs/smf/context"
	"etrib5gc/nfs/smf/dataplane"
	"etrib5gc/util/dijkstra"
	"github.com/reogac/pfcp/message"
	"github.com/reogac/sbi"
	"github.com/reogac/sbi/apis/upf/n4sbi"
	"github.com/reogac/sbi/models"
	"github.com/reogac/utils"
	"github.com/sirupsen/logrus"
)

// represent a network interface at an UPF
type NetInf struct {
	id      string   //unique id in a  topo, compose of the node id, the network, and the interface index
	netname string   //network that this face connects to
	ip      net.IP   //ipv4 or ipv6
	local   *UpfNode //local node attached to this interface
	mtu     uint32
}

type UpfNode struct {
	*logrus.Entry
	id     string              // uuid generated by controller (from Callback)
	infs   map[string][]NetInf //inf identities as keys
	upfCli sbi.ConsumerClient
	upf    *dataplane.Upf
}

func createUpfNode(t *upfTopoMan, info *common.UpfInfo, sbiEp *models.EndpointInfo) (node *UpfNode, err error) {
	ret := &UpfNode{
		Entry: log.WithFields(logrus.Fields{
			"upf": sbiEp.Uuid,
		}),
		id:   sbiEp.Uuid,
		infs: make(map[string][]NetInf),
	}

	//check if UPF serves SMF's slice
	hasSmfSlice := false
	smfSlice := context.Snssai()
	for _, s := range info.Slices {
		if common.IsSliceEqual(smfSlice, &s) { //check if the UPF serving Smf's slice
			hasSmfSlice = true
		}
	}
	if !hasSmfSlice {
		err = fmt.Errorf("Upf not serve Smf's slice")
		return
	}
	//add N3, N9 interfaces
	for netname, inf := range info.INFs {
		if !context.HasTransportNetwork(netname) {
			continue
		}
		var ip net.IP
		if ip = net.ParseIP(inf.Addr); len(ip) == 0 {
			continue
		}

		oldlist := ret.infs[netname]
		ret.infs[netname] = append(oldlist, NetInf{
			netname: netname,
			ip:      ip,
			local:   ret,
			id:      fmt.Sprintf("%s-%s-%d", ret.id, netname, len(oldlist)),
		})
	}
	if len(ret.infs) == 0 {
		err = fmt.Errorf("Upf has no valid network interface")
		return
	}

	//create UPF sbi client
	if ret.upfCli, err = mesh.ConsumerFromEndpoint(sbiEp); err != nil {
		err = utils.WrapError("Create UPF client", err)
		return
	}

	//register SMF to the UPF for resource allocation
	epInfo := mesh.EndpointInfo()
	reqContent := message.AssociationRequest{
		Slice: *context.Snssai(),
		//	DataNetworks: dataNetworks,
	}
	reqContentBytes, _ := json.Marshal(&reqContent)

	associateReq := &message.PFCPAssociationSetupRequest{
		PFCPASReqFlags: reqContentBytes,
	}
	var associateRsp *message.PFCPAssociationSetupResponse
	if associateRsp, err = n4sbi.AssociationRequest(ret.upfCli, epInfo, associateReq); err != nil {
		return
	}
	if associateRsp.PFCPASRspFlags == nil {
		err = fmt.Errorf("Invalid association setup response")
		return
	}
	//parse allocated resources
	rspContent := &message.AssociationResponse{}
	if err = json.Unmarshal(associateRsp.PFCPASRspFlags, rspContent); err != nil {
		return
	}
	teidL := rspContent.TeidRange.LowerBound
	teidU := rspContent.TeidRange.UpperBound
	log.Tracef("Allocated TEID range:%d-%d", teidL, teidU)
	ret.upf = dataplane.NewUpf(ret.upfCli, ret, teidL, teidU)
	node = ret
	return
}

func (node *UpfNode) GetId() string {
	return node.id
}

//check if the node can reach to one of the transport networks in a given list
func (node *UpfNode) IsReachable(nets []string) bool {
	for network, _ := range node.infs {
		for _, netname := range nets {
			if netname == network {
				return true
			}
		}
	}

	return false
}

// get all interfaces to the transport networks in a given list
func (node *UpfNode) getFacesForNets(nets []string) (foundinfs []NetInf) {
	for network, infs := range node.infs {
		for _, netname := range nets {
			if netname == network {
				foundinfs = append(foundinfs, infs...)
				break
			}
		}
	}
	return
}

func (node *UpfNode) getInfs() (all []NetInf) {
	for _, infs := range node.infs {
		all = append(all, infs...)
	}
	return
}

// NOTE: node must have net interfaces
func (node *UpfNode) pickRandomFace() NetInf {
	allFaces := []NetInf{}
	for _, infs := range node.infs {
		allFaces = append(allFaces, infs...)
	}
	selectedIndex := rand.Intn(len(allFaces))

	return allFaces[selectedIndex]
}

func (node *UpfNode) internalEdges() (edges []dijkstra.EdgeInfo) {
	nets := [][]NetInf{}
	//for every networks
	for _, infs := range node.infs {
		nets = append(nets, infs)
	}
	for i := 0; i < len(nets)-1; i++ {
		for j := i + 1; j < len(nets); j++ {
			for _, f1 := range nets[i] {
				for _, f2 := range nets[j] {
					edges = append(edges, dijkstra.EdgeInfo{
						A: f1.id,
						B: f2.id,
						W: 1,
					})
				}
			}
		}
	}
	return
}

func (node *UpfNode) hasDnn(dnn string) bool {
	//TODO
	return true
}

func (node *UpfNode) String() string {
	var b bytes.Buffer
	b.WriteString(fmt.Sprintf("id=%s", node.id))

	infs := []string{}
	for netname, items := range node.infs {
		ips := []string{}
		for _, item := range items {
			ips = append(ips, item.ip.String())
		}
		infs = append(infs, fmt.Sprintf("%s:%s", netname, strings.Join(ips, "/")))
	}
	if len(infs) > 0 {
		b.WriteString(";\tinfs = " + strings.Join(infs, ", "))
	}

	return b.String()
}
