all:
  hosts:
    k3s-server-1:
      ansible_host: k3s-server-1
    k3s-agent-1:
      ansible_host: k3s-agent-1
    k3s-agent-2:
      ansible_host: k3s-agent-2

  children:
    masters:
      hosts:
        k3s-server-1:
    workers:
      hosts:
        k3s-agent-1:
        k3s-agent-2:

  vars:
    ansible_user: vagrant
    ansible_ssh_common_args: "-F /home/hieu/5gcore-deploy/.vagrant-ssh-config"
    ansible_python_interpreter: /usr/bin/python3
