- name: Check if k3s agent is already installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Install k3s agent
  shell: |
    curl -sfL https://get.k3s.io | \
      K3S_URL=https://{{ hostvars['k3s-server']['master_ip'] }}:6443 \
      K3S_TOKEN={{ hostvars['k3s-server']['k3s_node_token'] }} \
      INSTALL_K3S_EXEC="agent \
        --node-ip {{ ansible_host }} \
        --flannel-iface eth1" \
      sh -
  when: not k3s_binary.stat.exists
