Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.ssh.insert_key = false
  config.ssh.forward_agent = false
  config.ssh.keep_alive = true
  config.ssh.connect_timeout = 60
  config.vm.boot_timeout = 900

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  nodes = {
    "k3s-server"  => { ip: "192.168.56.10", cpus: 4, memory: 4096 },
    "k3s-agent1"  => { ip: "192.168.56.11", cpus: 4, memory: 4096 },
    "k3s-agent2"  => { ip: "192.168.56.12", cpus: 4, memory: 4096 }
  }

  nodes.each do |name, info|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: info[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = info[:memory]
        vb.cpus = info[:cpus]
      end

      node.vm.provision "shell",
        privileged: true,
        inline: <<-SHELL
          sleep 10
        SHELL
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/deploy.yml"
    ansible.inventory_path = "ansible/inventory.ini"
    ansible.become = true
    ansible.extra_vars = {
      k3s_token: "b5gc-k3s-cluster-token"
    }
  end
end
