package uecontext

import (
	"context"
	"etrib5gc/common"
	"etrib5gc/nfs/amf/sm"
	"github.com/reogac/nas"
	"github.com/reogac/sbi/models"
	"github.com/reogac/utils"
	"github.com/reogac/utils/idgen"
	"math"
	"net/http"
	"sync"
	"time"
)

const (
	T3565_DURATION time.Duration = 5 * time.Second
	T3565_MAX_CNT  int           = 2
)

type N1N2Context struct {
	Request     *models.N1N2MessageTransferRequest
	Response    *models.N1N2MessageTransferRspData
	ErrResponse *models.N1N2MessageTransferError

	pending *PendingN1N2 //pending N1N2 to wait for UE after paging/notifying
}

type N1MessageInfo struct {
	payload   []byte
	n1Type    uint8
	sessionId *uint8
}

type PendingN1N2 struct {
	smCtx        *sm.SmContext //for N2SmInfo
	n2SmInfo     []byte
	n2SmInfoType models.N2SmInfoType
	n1Msg        *N1MessageInfo

	id       uint16 //id generated by AMF
	isPaging bool   // UE is notify by paging or 3GPP access notification?
	isGpp    bool   //is 3GPP access
	t3565    common.Timer
}

func (ueCtx *UeContext) validateN1N2MessageTransferRequest(n1n2 *N1N2Context) bool {
	req := n1n2.Request
	reqInfo := req.JsonData
	pending := new(PendingN1N2) //for building N1N2 messages to forward to UE/RAN

	//analyze N2Info
	if reqInfo.N2InfoContainer != nil {
		switch reqInfo.N2InfoContainer.N2InformationClass {
		case models.N2INFORMATIONCLASS_SM: //only accept N2SmInfo
			smInfo := reqInfo.N2InfoContainer.SmInfo
			//make sure to have SmInfo
			if smInfo == nil {
				ueCtx.Warnf("Empty SmInfo in N2InfoContainer, N1N2Message not transfered")
				n1n2.ErrResponse = &models.N1N2MessageTransferError{
					Error: models.ProblemDetails{
						Status: http.StatusBadRequest,
						Detail: "Empty SmInfo in N2InfoContainer",
					},
				}
				return false
			}
			//make sure to have N2InfoContent
			if smInfo.N2InfoContent == nil {
				ueCtx.Warnf("Empty N2InfoContent, N1N2Message not transfered")
				n1n2.ErrResponse = &models.N1N2MessageTransferError{
					Error: models.ProblemDetails{
						Status: http.StatusBadRequest,
						Detail: "Empty N2InfoContent",
					},
				}
				return false

			}

			//find SmContext for the N2SmInfo
			sessionId := uint8(smInfo.PduSessionId)
			if pending.smCtx = ueCtx.findSmContext(sessionId); pending.smCtx == nil {
				ueCtx.Errorf("N1N2Message is not linked to a SmContext[%d]", sessionId)
				n1n2.ErrResponse = &models.N1N2MessageTransferError{
					Error: models.ProblemDetails{
						Status: http.StatusNotFound,
						Detail: "Sm context not found",
					},
				}
				return false
			}
			//make sure to have valid NgapIeType
			pending.n2SmInfo = req.BinaryDataN2Information
			if pending.n2SmInfoType = getN2SmInfoType(smInfo.N2InfoContent.NgapIeType); len(pending.n2SmInfoType) == 0 {
				ueCtx.Warnf("N1N2Message have N2SmInfo without specifying NgapIeType")
				n1n2.ErrResponse = &models.N1N2MessageTransferError{
					Error: models.ProblemDetails{
						Status: http.StatusBadRequest,
						Detail: "Empty NgapIeType",
					},
				}
				return false

			}
		default:
			ueCtx.Warnf("N1N2Message with unsupported N2 Information type [%s]", reqInfo.N2InfoContainer.N2InformationClass)
			n1n2.ErrResponse = &models.N1N2MessageTransferError{
				Error: models.ProblemDetails{
					Status: http.StatusNotImplemented,
					Detail: "Non-N2SmInfo transfer not implemented",
				},
			}
			return false
		}
	}

	//analyze N1Message
	if reqInfo.N1MessageContainer != nil {
		pending.n1Msg = &N1MessageInfo{
			payload: req.BinaryDataN1Message,
			n1Type:  getN1Type(reqInfo.N1MessageContainer.N1MessageClass),
		}
		if reqInfo.PduSessionId != nil {
			pending.n1Msg.sessionId = newUint8(uint8(*reqInfo.PduSessionId))
		}
	}

	//get target access
	access := req.JsonData.TargetAccess

	if len(access) == 0 { //if request does not specify a target access, use current access of the session
		if pending.smCtx == nil {
			ueCtx.Warnf("Request without TargetAccess")
			n1n2.ErrResponse = &models.N1N2MessageTransferError{
				Error: models.ProblemDetails{
					Status: http.StatusBadRequest,
					Detail: "No TargetAccess",
				},
			}
			return false
		} else {
			pending.isGpp = pending.smCtx.IsGpp()
		}
	} else {
		pending.isGpp = isGpp(access)
	}
	n1n2.pending = pending
	return true
}

type N1N2Man struct {
	pendings    map[uint16]*PendingN1N2
	mutex       sync.Mutex
	statusIdGen idgen.Generator[uint16]
}

func newN1N2Man() N1N2Man {
	return N1N2Man{
		pendings:    make(map[uint16]*PendingN1N2),
		statusIdGen: idgen.NewGenerator[uint16](0, math.MaxUint16),
	}
}
func (m *N1N2Man) add(n1n2 *PendingN1N2) {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	n1n2.id = m.statusIdGen.Allocate()
	m.pendings[n1n2.id] = n1n2
}

func (m *N1N2Man) remove(id uint16) {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	if _, ok := m.pendings[id]; ok {
		delete(m.pendings, id)
		m.statusIdGen.Free(id)
	}
}

// add the N1N2Message then return a generated identity
// TODO: create a go routine to wait for UE or timeout then notify
// N1N2MessageTransfer requester (SMF ...)
func (ueCtx *UeContext) addPendingN1N2(n1n2 *PendingN1N2) {
	_uePool.n1n2man.add(n1n2)
	ueCtx.n1n2Mu.Lock()
	ueCtx.n1n2 = n1n2
	ueCtx.n1n2Mu.Unlock()
}

func removePendingN1N2(n1n2 *PendingN1N2) {
	if n1n2 == nil {
		return
	}
	_uePool.n1n2man.remove(n1n2.id)
}

func (m *N1N2Man) clean() {
	m.mutex.Lock()
	defer m.mutex.Unlock()
	for id, _ := range m.pendings {
		m.statusIdGen.Free(id)
	}
	m.pendings = make(map[uint16]*PendingN1N2)
}

func (ueCtx *UeContext) ReceiveN1N2(ctx context.Context, msg *models.N1N2MessageTransferRequest) (rsp *models.N1N2MessageTransferRspData, ersp *models.N1N2MessageTransferError) {
	ueCtx.Debugf("Receive a N1N2Message transfer request from SMF")
	if msg.JsonData == nil {
		ueCtx.Errorf("Receive a N1N2Message empty content")
		ersp = &models.N1N2MessageTransferError{
			Error: models.ProblemDetails{
				Status: http.StatusBadRequest,
				Detail: "Empty N1N2Message conternt",
			},
		}
		return

	}

	//create a N1N2Context for the N1N2 message transfering task
	n1n2 := &N1N2Context{
		Request: msg,
	}
	ueCtx.handleN1N2(ctx, n1n2)
	return n1n2.Response, n1n2.ErrResponse
}

func (ueCtx *UeContext) hasN1N2Pending() bool {
	ueCtx.n1n2Mu.Lock()
	defer ueCtx.n1n2Mu.Unlock()
	return ueCtx.n1n2 != nil
}

// main procedure to handle N1N2 message transfering
func (ueCtx *UeContext) handleN1N2(ctx context.Context, info *N1N2Context) {
	if ueCtx.hasN1N2Pending() {
		//there is a pending N1N2
		ueCtx.Warnf("There is a pending N1N2Message, new request is not handled")
		info.ErrResponse = &models.N1N2MessageTransferError{
			Error: models.ProblemDetails{
				Status: http.StatusConflict,
				Detail: "Pending N1N2 existed",
			},
		}
		return
	}

	//1. process and validate request content
	if !ueCtx.validateN1N2MessageTransferRequest(info) {
		return
	}

	//2. if the UE is in CM_CONNECTED for the given access, forward the message
	//to the state machine of that access
	if ranUe := ueCtx.getRanUe(info.pending.isGpp); ranUe != nil {
		ueCtx.Tracef("In CM_CONNECTED, forward N1N2")
		ueCtx.forwardN1N2TransferDownlink(ranUe, ctx, info)
	} else {
		ueCtx.Tracef("In CM_IDLE, need Paging/Notification")
		//3. else: UE is in CM_IDLE
		if info.pending.isGpp {
			if !ueCtx.gpp.registered {
				//not registered on 3GPP
				info.ErrResponse = &models.N1N2MessageTransferError{
					Error: models.ProblemDetails{
						Status: http.StatusConflict,
						Detail: "Not registered on 3GPP access",
					},
				}
				return
			}
			//3a. if access is 3GPP
			//3a1. non-3gpp access is connected -> send
			//notification through non-3gpp access
			//3a2. else: send paging
			if ranUe := ueCtx.nonGpp.ranUe; ranUe != nil {
				//send notification to non 3GPP face
				ueCtx.Infof("Ask RanUe to send Notification")
				ueCtx.notifyN1N2TransferDownlink(ranUe, ctx, info)
			} else {
				ueCtx.doPaging(ctx, info)
			}
		} else {
			if !ueCtx.nonGpp.registered {
				//not registered on Non3GPP
				info.ErrResponse = &models.N1N2MessageTransferError{
					Error: models.ProblemDetails{
						Status: http.StatusConflict,
						Detail: "Not registered on Non3GPP access",
					},
				}
				return
			}

			//3b. access is Non-3GPP
			//3b1. 3gpp access is connected -> send
			//notification through 3gpp access
			//3b2. else: send paging

			if ranUe := ueCtx.gpp.ranUe; ranUe != nil {
				//send notification to 3GPP face
				ueCtx.Infof("Ask RanUe to send Notification")
				ueCtx.notifyN1N2TransferDownlink(ranUe, ctx, info)
			} else { //page 3GPP access
				ueCtx.doPaging(ctx, info)
			}
		}
	}
	return
}

//send N1 message and N2SmInfo message toward RAN/UE
//for now we only support N2SmInfo (no other types of N2)
func (ueCtx *UeContext) forwardN1N2TransferDownlink(ranUe RanUe, ctx context.Context, n1n2 *N1N2Context) {
	var err error
	smCtx := n1n2.pending.smCtx

	n1 := n1n2.pending.n1Msg
	var nasPdu []byte
	//if there is a N1 message, we need to build NasDownlink message to wrap it
	if n1 != nil {
		if nasPdu, err = ueCtx.buildDlNasTransport(ranUe.IsGpp(), n1.n1Type, n1.payload, n1.sessionId, nil, nil, 0); err != nil {
			ueCtx.Errorf("Fail to build NasDl for N1 message transfer: %+v", err)
			n1n2.Response = &models.N1N2MessageTransferRspData{
				Cause: models.N1N2MESSAGETRANSFERCAUSE_FAILURE_CAUSE_UNSPECIFIED,
			}
			return
		}
	}

	if smCtx != nil { //send n2SmInfo (may embed N1Sm)
		if n1 != nil && n1.n1Type == nas.PayloadContainerTypeN1SMInfo { //if N1 is from SMF, included it
			ueCtx.Tracef("Forward N1N2Sm together")
			if err = ueCtx.sendN2SmInfoDownlink(ranUe.IsGpp(), smCtx, nasPdu, n1n2.pending.n2SmInfo, n1n2.pending.n2SmInfoType); err != nil {
				ueCtx.Errorf("Fail to forward N1Sm and N2SmInfo downlink for session %d: %v", smCtx.GetId(), err)
				n1n2.Response = &models.N1N2MessageTransferRspData{
					Cause: models.N1N2MESSAGETRANSFERCAUSE_AN_NOT_RESPONDING,
				}
			}

		} else { //only send N2SmInfo
			ueCtx.Tracef("Forward Only N2SmInfo")
			if err = ueCtx.sendN2SmInfoDownlink(ranUe.IsGpp(), smCtx, nil, n1n2.pending.n2SmInfo, n1n2.pending.n2SmInfoType); err != nil {
				ueCtx.Errorf("Fail to forward N2SmInfo downlink for session %d: %v", smCtx.GetId(), err)
				n1n2.Response = &models.N1N2MessageTransferRspData{
					Cause: models.N1N2MESSAGETRANSFERCAUSE_AN_NOT_RESPONDING,
				}
			}
		}
	}
	if n1 != nil && (n1.n1Type != nas.PayloadContainerTypeN1SMInfo || smCtx == nil) { //send N1Message separately
		if err = ranUe.SendNas(nasPdu); err != nil {
			ueCtx.Errorf("Fail to send NasDl for N1 message transfer: %+v", err)
			n1n2.Response = &models.N1N2MessageTransferRspData{
				Cause: models.N1N2MESSAGETRANSFERCAUSE_AN_NOT_RESPONDING,
			}
		} else {
			ueCtx.Infof("N1 message from N1N2MessageTransferRequest was sent to UE")
		}
	}
	//response not set means N1N2 message has been sent downlink, we will set
	//the response now
	if n1n2.Response == nil {
		n1n2.Response = &models.N1N2MessageTransferRspData{
			Cause: models.N1N2MESSAGETRANSFERCAUSE_N1_N2_TRANSFER_INITIATED,
		}
	}

}

// send a notification to RAN, queue the N1N2 message
func (ueCtx *UeContext) notifyN1N2TransferDownlink(ranUe RanUe, ctx context.Context, n1n2 *N1N2Context) (err error) {
	ueCtx.Debugf("Notify N1N2")
	if err := ueCtx.sendNotification(ranUe, n1n2.pending.isGpp); err == nil {
		n1n2.Response = &models.N1N2MessageTransferRspData{
			Cause: models.N1N2MESSAGETRANSFERCAUSE_ATTEMPTING_TO_REACH_UE,
		}

		// queue n1n2 transfer request
		n1n2.pending.isPaging = false
		ueCtx.addPendingN1N2(n1n2.pending)
	} else {
		ueCtx.Errorf("Fail to send notification for N1N2MessagerTransfer: %+v", err)
		n1n2.Response = &models.N1N2MessageTransferRspData{
			Cause: models.N1N2MESSAGETRANSFERCAUSE_AN_NOT_RESPONDING,
		}
	}

	return
}

func (ueCtx *UeContext) sendNotification(ranUe RanUe, targetIsGpp bool) error {
	msg := new(nas.Notification)
	if targetIsGpp {
		msg.AccessType = nas.AccessTypeNon3GPP
	} else {
		msg.AccessType = nas.AccessType3GPP
	}
	msg.SetSecurityHeader(nas.NasSecBoth) //there must be an security context
	if pdu, err := nas.EncodeMm(ueCtx.getNasContext(), msg, ranUe.IsGpp()); err == nil {
		if err = ranUe.SendNas(pdu); err != nil {
			return utils.WrapError("Send NAS Notification", err)
		}
	} else {
		return utils.WrapError("Encode NAS Notification", err)
	}
	return nil
}

// notify SMF of failure to forward N1N2 messages
func (ueCtx *UeContext) notifyN1N2Failure(onlyN1 bool) {
	//TODO: send notification to SMF
	removePendingN1N2(ueCtx.n1n2)
	ueCtx.n1n2Mu.Lock()
	ueCtx.n1n2 = nil
	ueCtx.n1n2Mu.Unlock()
}

// handle N2SmInfo transfer to SMF
func (ueCtx *UeContext) ForwardN2SmInfoUplink(req *models.N2SmInfoUplinkTransport) {
	msg := &models.SmContextUpdateData{
		N2SmInfo: &models.RefToBinaryData{
			ContentId: "N2SmInfo",
		},
		UeLocation: &ueCtx.loc,
	}

	jobs := []func(){}

	for _, transfer := range req.Transfers {
		jobs = append(jobs, func() {
			if smCtx := ueCtx.findSmContext(uint8(transfer.SessionId)); smCtx == nil {
				ueCtx.Errorf("No SmContext found for session %d to forward N2Info", transfer.SessionId)
			} else {
				msg.N2SmInfoType = transfer.N2SmInfoType
				if rsp, ersp, err := smCtx.SendUpdateSmContext(msg, nil, transfer.N2SmInfo); err != nil {
					ueCtx.Errorf("Fail to send UpdateSmContext for session %d: %+v", smCtx.GetId(), err)
				} else {
					ueCtx.Infof("N2SmInfo is forwarded to SMF")
					ueCtx.forwardUpdateSmContextResponsesDownlink(smCtx, rsp, ersp)
				}
			}
		})
	}
	sendTasks(jobs)
	return
}

//extract N1Sm and N2SmInfo from UpdateSmContext responses
func (ueCtx *UeContext) processUpdateSmContextResponses(smCtx *sm.SmContext, rsp *models.UpdateSmContextResponse, ersp *models.UpdateSmContextErrorResponse) (n2 *models.N2SmInfoDownlinkContent, n1 []byte) {
	sId := smCtx.GetId()
	snssai := smCtx.GetSlice()
	if rsp != nil && rsp.JsonData != nil {
		if len(rsp.BinaryDataN2SmInformation) > 0 {
			n2 = &models.N2SmInfoDownlinkContent{
				SessionId:    int16(sId),
				N2SmInfo:     rsp.BinaryDataN2SmInformation,
				N2SmInfoType: rsp.JsonData.N2SmInfoType,
				Snssai:       snssai,
			}
		}

		var nasPdu []byte
		var err error
		if n1Sm := rsp.BinaryDataN1SmMessage; len(n1Sm) > 0 { //build downlink Nas message
			if nasPdu, err = ueCtx.buildDlNasTransport(smCtx.IsGpp(), nas.PayloadContainerTypeN1SMInfo, n1Sm, &sId, nil, nil, 0); err != nil {
				ueCtx.Errorf("Fail to build DownlinkNasTransport for N1Sm: %+v", err)
			} else {
				if n2 != nil {
					n2.NasPdu = nasPdu
				} else {
					n1 = nasPdu
				}
			}
		}
		return
	}
	if ersp != nil && ersp.JsonData != nil {
		if len(ersp.BinaryDataN2SmInformation) > 0 {
			n2 = &models.N2SmInfoDownlinkContent{
				SessionId:    int16(sId),
				N2SmInfo:     ersp.BinaryDataN2SmInformation,
				N2SmInfoType: ersp.JsonData.N2SmInfoType,
				Snssai:       snssai,
			}
		}

		var nasPdu []byte
		var err error
		if n1Sm := ersp.BinaryDataN1SmMessage; len(n1Sm) > 0 { //build downlink Nas message
			if nasPdu, err = ueCtx.buildDlNasTransport(smCtx.IsGpp(), nas.PayloadContainerTypeN1SMInfo, n1Sm, &sId, nil, nil, 0); err != nil {
				ueCtx.Errorf("Fail to build DownlinkNasTransport for N1Sm: %+v", err)
			} else {
				if n2 != nil {
					n2.NasPdu = nasPdu
				} else {
					n1 = nasPdu
				}
			}
		}
	}

	return
}

//send N1Sm, N2SmInfo from UpdateSmContext responses to gnb/Ue
func (ueCtx *UeContext) forwardUpdateSmContextResponsesDownlink(smCtx *sm.SmContext, rsp *models.UpdateSmContextResponse, ersp *models.UpdateSmContextErrorResponse) {
	if n2, n1 := ueCtx.processUpdateSmContextResponses(smCtx, rsp, ersp); n2 != nil {
		ueCtx.sendN2SmInfoDownlink(smCtx.IsGpp(), smCtx, n1, n2.N2SmInfo, n2.N2SmInfoType)
	} else {
		ueCtx.sendN2SmInfoDownlink(smCtx.IsGpp(), smCtx, n1, nil, "")
	}
}

//send N2SmInfo downlink with N1Sm embeded
//if no N2SmInfo provided, N1Sm is sent
func (ueCtx *UeContext) sendN2SmInfoDownlink(isGpp bool, smCtx *sm.SmContext, n1SmDl, n2SmInfo []byte, n2SmInfoType models.N2SmInfoType) error {
	ranUe := ueCtx.getRanUe(isGpp)
	sId := smCtx.GetId()
	if len(n2SmInfoType) == 0 {
		//if there is no N2SmInfo, send N1Sm (DownlinkNasTransport)
		if len(n1SmDl) > 0 { //only N1Sm
			if err := ranUe.SendNas(n1SmDl); err != nil {
				return utils.WrapError("Send N1Sm downlink", err)
			} else {
				ueCtx.Infof("N1Sm is forwarded to gnB")
			}
		}
	} else { //there is N2SmInfo, include N1Sm (DownlinkNasTransport) to send
		if err := ranUe.SendN2SmInfoDownlink([]models.N2SmInfoDownlinkContent{
			models.N2SmInfoDownlinkContent{
				N2SmInfo:     n2SmInfo,
				N2SmInfoType: n2SmInfoType,
				SessionId:    int16(sId),
				NasPdu:       n1SmDl,
				Snssai:       smCtx.GetSlice(),
			},
		}, nil); err != nil {
			return utils.WrapError("Send N2SmInfoDownlink", err)
		} else {
			ueCtx.Infof("N2SmInfo is is forwarded to gnB")
		}
	}
	return nil
}
