package gateway

import (
	"bytes"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"etrib5gc/common"
	"etrib5gc/logctx"
	"etrib5gc/mesh/gateway/monitoring"
	"etrib5gc/mesh/gateway/oambackend"
	"etrib5gc/mesh/models"
	"etrib5gc/nfs/app"
	"fmt"
	"github.com/reogac/utils"
	"github.com/reogac/utils/httpw"
	"github.com/sirupsen/logrus"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/gin-gonic/gin"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

const (
	REGISTER_INTERVAL int    = 5 //second
	GW_LABEL_PREFIX   string = "_gw-"
)

func init() {
	gin.SetMode(gin.ReleaseMode)
}

var log *logrus.Entry

type Gateway struct {
	server *httpw.Server
	id     string //uuid generated by the controller

	registeredAddr string

	name    string //gateway server certificate name for mTLS verfication
	ctrlUrl string //controller URI
	cli     *httpw.Client
	quit    chan bool

	peers *Peers

	hb     int
	epman  *EndpointManager //endpoint manager
	wg     sync.WaitGroup
	labels map[string]string

	k8sCli       *kubernetes.Clientset
	k8sNameSpace string

	cert   *tls.Certificate
	caPool *x509.CertPool
}

type epEvent struct {
	evtype uint8
	dat    interface{}
}

func (gw *Gateway) Init(ctx *app.Context) error {
	//init logger
	log = logctx.Entry(nil)

	var cfg Config

	if err := json.Unmarshal(ctx.ConfigData, &cfg); err != nil {
		return utils.WrapError("Unmarshal config", err)
	}

	gw.peers = newPeers()

	gw.hb = cfg.Heartbeat
	gw.labels = make(map[string]string)
	gw.quit = make(chan bool)

	//add a dummy label
	for k, v := range cfg.Labels {
		gw.labels[GW_LABEL_PREFIX+k] = v
	}

	if gw.k8sNameSpace = os.Getenv("POD_NAMESPACE"); len(gw.k8sNameSpace) > 0 { //in K8s
		if k8sConfig, err := rest.InClusterConfig(); err != nil {
			return utils.WrapError("Get K8s client configuration", err)
		} else {
			if gw.k8sCli, err = kubernetes.NewForConfig(k8sConfig); err != nil {
				return utils.WrapError("Create client set", err)
			}
		}
	}

	if gw.hb < 5000 {
		gw.hb = 5000
	}

	if host, port, err := common.ParseHostPort(cfg.Controller, "127.0.0.1", "8888"); err != nil {
		return utils.WrapError("Parse controller address", err)
	} else {
		gw.ctrlUrl = fmt.Sprintf("%s:%d", host, port)
	}

	log.Infof("Controller address: %s", gw.ctrlUrl)

	//create http server
	bindIp, bindPort, err := common.ParseHostPort(cfg.Bind, "0.0.0.0", "7777")
	if err != nil {
		return utils.WrapError("Parse binding address", err)
	}

	gw.server = httpw.NewServer(httpw.Options{
		Addr:   fmt.Sprintf("%s:%d", bindIp, bindPort),
		Cert:   ctx.Cert,
		CaPool: ctx.CaPool,
		Routes: gw.makeHttpRoutes(),
	})

	if host, port, err := common.ParseHostPort(cfg.RegisteredAddr, bindIp, fmt.Sprintf("%d", bindPort)); err != nil {
		return utils.WrapError("Parse gateway registered address", err)
	} else {
		if host == "0.0.0.0" {
			if hostIp, err := common.GetPrimaryIP(); err != nil {
				return utils.WrapError("Get local Ip address", err)
			} else {
				host = hostIp.String()
			}
		}

		log.Infof("Registered address: %s:%d", host, port)
		gw.registeredAddr = fmt.Sprintf("%s:%d", host, port)
	}

	if len(ctx.CertName) > 0 {
		log.Infof("Gateway certificate's subject CN: %s", ctx.CertName)
	}
	gw.name = ctx.CertName

	//backend for monitoring API
	monServ := monitoring.New(&oamApi{
		gw: gw,
	})

	gw.server.AddRoutes("mon", monServ.MakeHttpRoutes())

	oamHandler := oambackend.NewOamHandler(&oamApi{
		gw: gw,
	})
	gw.server.AddRoutes("oam", oamHandler.Routes())

	//create http client
	gw.cli = httpw.NewClient(&ctx.Cert, ctx.CaPool, ctx.String("ctrl"))
	gw.cert = &ctx.Cert
	gw.caPool = ctx.CaPool

	return nil
}

func (gw *Gateway) makeHttpRoutes() []httpw.Route {
	return []httpw.Route{
		httpw.Route{ //endpoint registers
			Method:  http.MethodPost,
			Pattern: "/register",
			Handler: gw.onRegister,
		},
		httpw.Route{ //endpoint deregisters
			Method:  http.MethodPost,
			Pattern: "/deregister/:epId",
			Handler: gw.onDeregister,
		},
		httpw.Route{ //endpoint subscribes
			Method:  http.MethodPost,
			Pattern: "/subscribe/:epId",
			Handler: gw.onSubscribe,
		},
		httpw.Route{ //endpoint activates
			Method:  http.MethodPost,
			Pattern: "/activate/:epId",
			Handler: gw.onActivate,
		},
		httpw.Route{ //controller sends updates to endpoint
			Method:  http.MethodGet,
			Pattern: "/get/:epId",
			Handler: gw.onGetEndpoint,
		},
		httpw.Route{ //controller sends updates to endpoint
			Method:  http.MethodPost,
			Pattern: "/update/:epId",
			Handler: gw.onEndpointUpdate,
		},
		httpw.Route{ //controller pings
			Method:  http.MethodGet,
			Pattern: "/ping",
			Handler: gw.onPing,
		},
		httpw.Route{ //sbi reverse proxy
			Method:  "ANY",
			Pattern: "/sbi/:epId/*any",
			Handler: gw.onSbi,
		},
		httpw.Route{ //agent reverse proxy
			Method:  "ANY",
			Pattern: "/agent/:epId/*any",
			Handler: gw.onAgent,
		},
	}
}

func (gw *Gateway) Run() (err error) {
	//start registration
	for {
		//do registering here
		if err := gw.register(); err == nil {
			break
		} else {
			err = utils.WrapError("Gateway registering", err)
		}
		t := time.NewTimer(time.Duration(REGISTER_INTERVAL) * time.Second)
		select {
		case <-t.C:
			continue
		case <-gw.quit:
			err = fmt.Errorf("Forced termination")
			return
		}
	}

	//create endpoint manager
	gw.epman = newEndpointManager(gw)

	//start http server
	if err = gw.server.Start(); err != nil {
		return
	}
	log.Infof("Gateway listen to %s", gw.server.Srv.Addr)
	return
}

func (gw *Gateway) Stop() {
	log.Info("Gateway is terminating")
	close(gw.quit)
	if gw.epman != nil {
		gw.server.Stop()
		gw.deregister()
		gw.epman.close()
	}
	gw.wg.Wait()
}

func (gw *Gateway) onRegister(ctx *gin.Context) {
	log.Debugf("Receive an endpoint registration request")
	var err error
	var dat []byte
	var msg models.RegistrationRequest
	//parse message
	if dat, err = ioutil.ReadAll(ctx.Request.Body); err != nil {
		ctx.String(http.StatusBadRequest, err.Error())
		return
	}

	if err = json.Unmarshal(dat, &msg); err != nil {
		ctx.String(http.StatusBadRequest, err.Error())
		return
	}

	//create a new endpoint from the request
	var ep *Endpoint
	if ep, err = gw.createEndpoint(&msg); err != nil {
		log.Errorf("Fail to create endpoint from request: %+v", err)
		ctx.String(http.StatusBadRequest, "Failed to create endpoint")
	}

	//check if is the endpoint already registered
	//OR we need to remove the old one
	if old := gw.epman.findBySbiId(ep.sbiUrl); old != nil {
		log.Warnf("Registering endpoint existed: %s", old.sbiUrl)
		//re-sent the last registration response
		ctx.JSON(http.StatusCreated, &models.RegistrationResponse{
			Id:   old.id,
			GwId: gw.id,
		})
		return
	}

	newReq := &models.RegistrationFwRequest{
		Labels: ep.labels,
		Active: msg.Active,
		Config: msg.Config,
	}

	//register the  endpoint to the controller
	msgBytes, _ := json.Marshal(newReq)

	log.Tracef("Forward registration request to controller")
	var httpRsp *http.Response

	url := fmt.Sprintf("%s/register/%s", gw.ctrlUrl, gw.id)
	if httpRsp, dat, err = gw.cli.Send(http.MethodPost, url, bytes.NewBuffer(msgBytes)); err != nil {
		log.Errorf("Fail to forward request to the controller: %+v", err)
		ctx.String(http.StatusBadGateway, "Fail to forward registration request to controller")
	}

	if httpRsp.StatusCode == http.StatusCreated {
		var rspMsg models.RegistrationResponse
		if err = json.Unmarshal(dat, &rspMsg); err == nil {
			log.Infof("Endpoint %s registered, server send id: %s", ep.sbiUrl, rspMsg.Id)
			//update then register the endpoint now
			rspMsg.GwId = gw.id
			gw.epman.registerEndpoint(ep, rspMsg.Id)
			//response to the endpoint
			ctx.JSON(http.StatusCreated, &rspMsg)
		} else {
			log.Errorf("Fail to parse response body: %+v", err)
			ctx.String(http.StatusInternalServerError, "Bad registration response from controller")
		}
	} else {
		//endpoint is not registered at controller, just forward the controller message back to the endpoint
		ctx.Data(httpRsp.StatusCode, "application/json", dat)
	}
}

func (gw *Gateway) onDeregister(ctx *gin.Context) {
	log.Debug("Receive endppoint deregistrationr equest")
	epId := ctx.Param("epId")

	var ep *Endpoint
	//check if is the endpoint already registered
	if ep = gw.epman.findByUuid(epId); ep == nil {
		log.Warnf("Endpoint %s not found for deregistration", epId)
		ctx.String(http.StatusNotFound, fmt.Sprintf("Endpoint %s not found", epId))
		return
	}

	//delete endpoint now
	ep.close()
	gw.sendEpDeletion(ep)

	ctx.String(http.StatusCreated, "OK")
}

func (gw *Gateway) onSubscribe(ctx *gin.Context) {
	log.Debug("Receive an subscription request")

	epId := ctx.Param("epId")
	url := fmt.Sprintf("%s/subscribe/%s", gw.ctrlUrl, epId)
	log.Tracef("Forward service subscription to the controller")

	if httpRsp, dat, err := gw.cli.Send(http.MethodPost, url, ctx.Request.Body); err != nil {
		log.Errorf("Fail to forward subscription to controller: %+v", err)
		ctx.String(http.StatusInternalServerError, "Fail to forward subscription request")
	} else {
		var msg models.SubscribeResponse
		if err := json.Unmarshal(dat, &msg); err != nil {
			ctx.String(http.StatusInternalServerError, "Received bad subscription response from the controller")
		} else {
			gw.rewriteSubscribeResponse(&msg)
			dat, _ = json.Marshal(&msg)
			ctx.Data(httpRsp.StatusCode, "application/json", dat)
		}
	}
}

func (gw *Gateway) onActivate(ctx *gin.Context) {
	log.Debug("Receive an endpoint activation update")

	epId := ctx.Param("epId")
	url := fmt.Sprintf("%s/activate/%s", gw.ctrlUrl, epId)
	log.Tracef("Forward endpoint activation notification to the controller")

	if httpRsp, dat, err := gw.cli.Send(http.MethodPost, url, ctx.Request.Body); err == nil {
		ctx.Data(httpRsp.StatusCode, "application/json", dat)
	} else {
		log.Errorf("Fail to forward activation request to controller: %+v", err)
		ctx.String(http.StatusInternalServerError, "Fail to forward activation request")
	}
}

func (gw *Gateway) onGetEndpoint(ctx *gin.Context) {
	log.Debugf("Receive a get endpoint request")
	epId := ctx.Param("epId")
	if ep := gw.epman.findByUuid(epId); ep == nil {
		//get it from the controller
		url := fmt.Sprintf("%s/get/%s", gw.ctrlUrl, epId)
		if httpRsp, dat, err := gw.cli.Send(http.MethodGet, url, nil); err == nil {
			ctx.Data(httpRsp.StatusCode, "application/json", dat)
		} else {
			log.Errorf("Fail to get endpoint information from controller: %+v", err)
			ctx.String(http.StatusInternalServerError, "Fail to get endpoint information from the controller")
		}
	} else {
		log.Tracef("Found local endpoint %s", epId)
		msg := ep.toModel()
		ctx.JSON(http.StatusOK, &msg)
	}
}

func (gw *Gateway) onEndpointUpdate(ctx *gin.Context) {
	//1. get  UUID
	epId := ctx.Param("epId")
	log.Debugf("Receive update for %s from the controller", epId)

	//2. search for endpoint
	var ep *Endpoint
	if ep = gw.epman.findByUuid(epId); ep == nil {
		log.Warnf("Endpoint not found to handle an update message: %s", epId)
		ctx.String(http.StatusNotFound, fmt.Sprintf("Endpoint:%s not found", epId))
		return
	}
	var updateData []byte
	var err error
	//3. update information for local endpoints
	if updateData, err = ioutil.ReadAll(ctx.Request.Body); err != nil {
		ctx.String(http.StatusBadRequest, err.Error())
		return
	}
	var msg models.EndpointUpdates
	if err = json.Unmarshal(updateData, &msg); err != nil {
		log.Errorf("Fail to decode an endpoint update message: %+v", err)
		ctx.String(http.StatusBadRequest, "Fail to decode update message")
		return
	}
	body := gw.rewriteUpdateMessage(&msg)

	//4. forward request to the endpoint
	url := fmt.Sprintf("http://%s/update", ep.agentUrl)
	httpReq, err := http.NewRequest(ctx.Request.Method, url, body)
	if err != nil {
		log.Errorf("Failed to create an http request: %+v", err)
		ctx.String(http.StatusInternalServerError, "Method error")
		return
	}

	if httpRsp, err := ep.cli.SendRequest(httpReq); err == nil {
		defer httpRsp.Body.Close()
		ctx.DataFromReader(httpRsp.StatusCode, httpRsp.ContentLength, "application/json", httpRsp.Body, nil)

	} else {
		log.Errorf("Fail to forward updates to endpoint: %+v", err)
		ctx.String(http.StatusServiceUnavailable, "Fail to forward update to endpoint")
	}
}

func (gw *Gateway) onPing(ctx *gin.Context) {
	log.Debugf("Receicve a ping message")
	ctx.JSON(http.StatusOK, gin.H{
		"message": "pong",
	})
}

func (gw *Gateway) removeEp(ep *Endpoint, notify bool) {
	gw.epman.removeEp(ep)
	if notify {
		gw.sendEpDeletion(ep)
	}
}
func (gw *Gateway) sendEpDeletion(ep *Endpoint) {
	log.Debugf("Send endpoint deletion [%s] to controller", ep.id)
	//notify controller
	url := fmt.Sprintf("%s/delete/%s", gw.ctrlUrl, ep.id)
	if httpRsp, _, err := gw.cli.Send(http.MethodDelete, url, nil); err != nil {
		log.Errorf("Fail to send deletion request to controller: %+v", err)
	} else if httpRsp.StatusCode != http.StatusCreated {
		log.Errorf("Controller did not handle deletion request: %d:%s", httpRsp.StatusCode, httpRsp.Status)
	}
}

// register to the service controller
func (gw *Gateway) register() (err error) {
	msg := &models.GwRegistrationRequest{
		Url:    gw.registeredAddr,
		Name:   gw.name,
		Labels: gw.labels,
	}

	reqMsg, _ := json.Marshal(msg)

	body := bytes.NewBuffer(reqMsg)
	url := fmt.Sprintf("%s/gw", gw.ctrlUrl)

	log.Debugf("Register to the controller")

	if httpRsp, dat, err := gw.cli.Send(http.MethodPost, url, body); err != nil {
		return utils.WrapError("Send request", err)
	} else {
		if httpRsp.StatusCode != http.StatusCreated {
			return fmt.Errorf("Registration failed [%d]: %s (%s)", httpRsp.StatusCode, httpRsp.Status, string(dat))
		} else {
			var rspMsg models.GwRegistrationResponse
			if err = json.Unmarshal(dat, &rspMsg); err == nil {
				gw.id = rspMsg.Id
				log.Infof("Gateway is registered, controller send registered Id: %s", rspMsg.Id)
			} else {
				err = utils.WrapError("Parse response", err)
			}

		}
	}

	return
}

// deregister to the service controller
func (gw *Gateway) deregister() (err error) {
	url := fmt.Sprintf("%s/gw/del/%s", gw.ctrlUrl, gw.id)
	log.Debugf("Send gateway deregistration: %s", url)
	_, _, err = gw.cli.Send(http.MethodPost, url, nil)
	return
}

//get peer gateway information
func (gw *Gateway) getPeer(id string) *PeerGw {
	if peer := gw.peers.get(id); peer != nil {
		return peer
	}
	url := fmt.Sprintf("%s/gw-info/%s", gw.ctrlUrl, id)

	log.Debugf("Get geteway information for %s", id)

	if httpRsp, dat, err := gw.cli.Send(http.MethodGet, url, nil); err != nil {
		log.Errorf("Fail to request Gw information: %+v", err)
		return nil
	} else {
		if httpRsp.StatusCode != http.StatusOK {
			log.Errorf("Get gateway information failed [%d]: %s (%s)", httpRsp.StatusCode, httpRsp.Status, string(dat))
			return nil
		} else {
			var info models.GatewayInfo
			if err = json.Unmarshal(dat, &info); err == nil {
				cli := httpw.NewClient(gw.cert, gw.caPool, info.CertName)
				return gw.peers.add(id, info.Url, cli)
			} else {
				err = utils.WrapError("Parse GatewayInfo", err)
			}

		}
	}

	return nil
}

func (gw *Gateway) rewriteSubscribeResponse(msg *models.SubscribeResponse) {
	endpoints := make(map[string]models.Endpoint)
	for id, item := range msg.Endpoints {
		if ep := gw.epman.findByUuid(id); ep != nil {
			newItem := item
			newItem.SbiUrl, newItem.SbiPrefix, newItem.Name = ep.sbiUrl, ep.sbiPrefix, ep.certName
			endpoints[id] = newItem
		} else {
			endpoints[id] = item
		}
	}
	msg.Endpoints = endpoints
}

func (gw *Gateway) rewriteUpdateMessage(msg *models.EndpointUpdates) io.Reader {
	for i, item := range msg.Join {
		if ep := gw.epman.findByUuid(item.Id); ep != nil {
			item.SbiUrl, item.SbiPrefix, item.Name = ep.sbiUrl, ep.sbiPrefix, ep.certName
			msg.Join[i] = item
		}
	}
	body := new(bytes.Buffer)
	json.NewEncoder(body).Encode(msg)
	return body
}
