- name: Wait until k8s-master exists
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get node k8s-master
  register: wait_master
  retries: 30
  delay: 10
  until: wait_master.rc == 0
  changed_when: false

- name: Wait until k8s-worker1 exists
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get node k8s-worker1
  register: wait_worker1
  retries: 30
  delay: 10
  until: wait_worker1.rc == 0
  changed_when: false

- name: Wait until k8s-worker2 exists
  shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf get node k8s-worker2
  register: wait_worker2
  retries: 30
  delay: 10
  until: wait_worker2.rc == 0
  changed_when: false

- name: Label master as control role
  shell: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf label node k8s-master
    {{ master_role_label_key }}=true --overwrite
  changed_when: false

- name: Label worker1 as centre role
  shell: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf label node k8s-worker1
    {{ worker1_role_label_key }}=true --overwrite
  changed_when: false

- name: Label worker2 as edge role
  shell: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf label node k8s-worker2
    {{ worker2_role_label_key }}=true --overwrite
  changed_when: false

- name: Label worker1 site=centre
  shell: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf label node k8s-worker1
    site=centre --overwrite
  changed_when: false

- name: Label worker2 site=edge
  shell: >
    kubectl --kubeconfig=/etc/kubernetes/admin.conf label node k8s-worker2
    site=edge --overwrite
  changed_when: false