apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf-10-102-dep
  namespace: etri6g
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amf
      amfSet: 10-102
  template:
    metadata:
      labels:
        app: amf
        amfSet: 10-102
        plmnId: 208-93
    spec:
      volumes:
        - name: amf-config
          configMap:
            name: amf-10-102-config

      containers:
        - name: amf
          image: b5gc-amf:latest
          imagePullPolicy: IfNotPresent
          command: ["./amf"]
          args: ["-c", "/etc/config/amf.json"]
          volumeMounts:
            - mountPath: /etc/config
              name: amf-config

          ports:
            - containerPort: 9001
            - containerPort: 7001

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-10-102-config 
  namespace: etri6g
data:
  amf.json: |
    {
      "plmnId": {
        "mcc": "208",
        "mnc": "93"
      },
      "amfSet":"10-102",
      "mesh": {
        "registrar": "10.100.100.21"
      }
    }

