apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf-dep
  namespace: etri6g
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcf
  template:
    metadata:
      labels:
        app: pcf
        plmnId: 208-93
    spec:
      volumes:
        - name: pcf-config
          configMap:
            name: pcf-config

      containers:
        - name: pcf
          image: b5gc-pcf:latest
          imagePullPolicy: IfNotPresent
          command: ["./pcf"]
          args: ["-c", "/etc/config/pcf.json"]
          volumeMounts:
            - mountPath: /etc/config
              name: pcf-config

          ports:
            - containerPort: 9001
            - containerPort: 7001
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config 
  namespace: etri6g
data:
  pcf.json: |
    {
      "plmnId": {
        "mcc": "208",
        "mnc": "93"
      },
      "mesh": {
        "registrarIp": "10.100.100.21"
      }
    }
