apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf-slice1-dep
  namespace: etri6g
spec:
  replicas: 5
  selector:
    matchLabels:
      app: smf
      slice: 1-010203
  template:
    metadata:
      labels:
        app: smf
        plmnId: 208-93
        slice: 1-010203
    spec:
      volumes:
        - name: smf-config
          configMap:
            name: smf-slice1-config

      containers:
        - name: smf
          image: b5gc-smf:latest
          imagePullPolicy: IfNotPresent
          command: ["./smf"]
          args: ["-c", "/etc/config/smf.json"]
          volumeMounts:
            - mountPath: /etc/config
              name: smf-config

          ports:
            - containerPort: 9001
            - containerPort: 7001

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-slice1-config 
  namespace: etri6g
data:
  smf.json: |
    {
      "plmnId": {
        "mcc": "208",
        "mnc": "93"
      },
      "slice": {
        "sst" : 1,
        "sd": "010203"
      },
      "mesh": {
        "registrar": "10.100.100.21"
      }
    }
