package ue

import (
	"etrib5gc/internal/eventmux"
	"etrib5gc/logctx"
	"etrib5gc/mesh"
	"etrib5gc/nfs/pran/context"
	"fmt"
	"github.com/reogac/utils/idgen"
	"github.com/sirupsen/logrus"
	"math"
	"net"
	"sync"
	"sync/atomic"
)

var _pool *UePool
var log *logrus.Entry

type UeMap map[int64]*UeContext

func newUeMap() UeMap {
	return make(map[int64]*UeContext)
}

type UePool struct {
	closed      int32              //indicator if PRAN is terminated
	cuNgapId2Ue UeMap              //map local Id (cuUeId) to Ue context
	conn2ue     map[net.Conn]UeMap //map ran connection to Ue context list of corresponding gnB
	ranId       string             //PRAN id that be used as a part of Ue ID to send to AMF
	mutex       sync.RWMutex
	ngapIdGen   idgen.Generator[int64] //Ngap generator for UeContext at PRAN
}

func isUePoolClosed() bool {
	return atomic.LoadInt32(&_pool.closed) == 1
}

var _exec *eventmux.Executor[UeContext]

func CreateUePool() *UePool {
	if _pool != nil {
		return _pool
	}
	log = logctx.Entry(logrus.Fields{
		"mod": "ue",
	})

	epInfo := mesh.EndpointInfo() //for build ranId
	l := &UePool{
		ngapIdGen: idgen.NewGenerator[int64](1, math.MaxInt64),
		ranId:     fmt.Sprintf("%s", epInfo.Uuid[:6]),
	}
	l.cuNgapId2Ue = newUeMap()
	l.conn2ue = make(map[net.Conn]UeMap)
	_pool = l
	_exec, _ = eventmux.NewExecutor[UeContext](
		context.MaxNumUes(), // workers
		128,                 // queue allowance
		eventmux.Options[UeContext]{
			Handler: handleEvent,
		},
	)

	return l
}

func CloseUePool() {
	if _pool == nil {
		return
	}
	//mark pool closed
	atomic.StoreInt32(&_pool.closed, 1)
	//close all UeContexts
	_pool.mutex.Lock()
	ueList := []*UeContext{}
	for _, ueCtx := range _pool.cuNgapId2Ue {
		ueList = append(ueList, ueCtx)
	}
	_pool.mutex.Unlock()

	log.Debugf("Remove all UEs")
	var wg sync.WaitGroup
	for _, ueCtx := range ueList {
		wg.Add(1)
		go func(iWg *sync.WaitGroup) {
			ueCtx.Kill()
			iWg.Done()
		}(&wg)
	}
	wg.Wait()
	_exec.Stop()
}

func RemoveUes(conn net.Conn) {
	log.Debugf("Remove all UEs for conn: %s", conn.RemoteAddr().String())
	var wg sync.WaitGroup

	for _, ueCtx := range _pool.getRanUePool(conn) {
		wg.Add(1)
		go func(iWg *sync.WaitGroup) {
			ueCtx.Kill()
			iWg.Done()
		}(&wg)
	}
	wg.Wait()

}

// get list of UeContexts from a gnB
func (p *UePool) getRanUePool(conn net.Conn) (list []*UeContext) {
	_pool.mutex.RLock()
	defer _pool.mutex.RUnlock()
	if r, ok := _pool.conn2ue[conn]; ok {
		for _, ueCtx := range r {
			list = append(list, ueCtx)
		}
	}
	return
}

// find an UeContext with ngap id generated by PRAN
func FindWithLocalId(cuNgapId int64) (ueCtx *UeContext) {
	_pool.mutex.RLock()
	defer _pool.mutex.RUnlock()
	ueCtx, _ = _pool.cuNgapId2Ue[cuNgapId]
	return
}

// find an UeContext from a gnB with RanNgapId
func FindWithRemoteId(conn net.Conn, ranNgapId int64) (ueCtx *UeContext) {
	_pool.mutex.RLock()
	defer _pool.mutex.RUnlock()
	if r, ok := _pool.conn2ue[conn]; ok {
		ueCtx, _ = r[ranNgapId]
	}
	return
}

// add a new UeContext to the pool. The UeContext must have
// (RanNgapId[RAN], cuNgapId[PRAN])
func (pool *UePool) add(ueCtx *UeContext) {
	pool.mutex.Lock()
	defer pool.mutex.Unlock()
	conn := ueCtx.ran.Conn()
	//then add the context
	log.Infof("Add UeContext [cuUeId = %d]", ueCtx.cuNgapId())
	pool.cuNgapId2Ue[ueCtx.cuNgapId()] = ueCtx
	if r, ok := pool.conn2ue[conn]; ok {
		r[ueCtx.ranNgapId] = ueCtx
	} else {
		pool.conn2ue[conn] = UeMap{
			ueCtx.ranNgapId: ueCtx,
		}
	}
}

func (pool *UePool) remove(ueCtx *UeContext) {
	pool.mutex.Lock()
	defer pool.mutex.Unlock()
	delete(pool.cuNgapId2Ue, ueCtx.cuNgapId())
	conn := ueCtx.ran.Conn()
	if r, ok := pool.conn2ue[conn]; ok {
		delete(r, ueCtx.ranNgapId)
	}
	pool.ngapIdGen.Free(ueCtx.cuNgapId())
	log.Infof("Remove UeContext [cuUeId=%d]", ueCtx.cuNgapId())
}
