{{- $root := . }}
{{- $nfs := dict "controller" .Values.controller "gateway" .Values.gateway -}}
{{- range $nfName := list "controller" "gateway" }}
{{- $nfConf := index $nfs $nfName }}
{{- if and $nfConf $nfConf.enabled $nfConf.serviceAccount $nfConf.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $nfConf.serviceAccount.name }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
    app: {{ $nfName }}
    {{- include "etrib5gc.labels" $root | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $root.Values.global.syncWave.rbac | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $nfConf.serviceAccount.role.name }}
  namespace: {{ $root.Values.global.namespace }}
  labels:
    app: {{ $nfName }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $root.Values.global.syncWave.rbac | quote }}
rules:
  {{- toYaml $nfConf.serviceAccount.role.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $nfConf.serviceAccount.name }}-binding
  namespace: {{ $root.Values.global.namespace }}
  labels:
    app: {{ $nfName }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $root.Values.global.syncWave.rbac | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $nfConf.serviceAccount.name }}
    namespace: {{ $root.Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ $nfConf.serviceAccount.role.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
