- name: Label agent1 as centre site
  shell: k3s kubectl label node k3s-agent1 site=centre --overwrite
  delegate_to: k3s-server
  changed_when: false

- name: Label agent2 as edge site
  shell: k3s kubectl label node k3s-agent2 site=edge --overwrite
  delegate_to: k3s-server
  changed_when: false

- name: Verify node labels
  shell: k3s kubectl get nodes --show-labels
  delegate_to: k3s-server
  register: node_labels
  changed_when: false

- name: Show node labels
  debug:
    msg: "{{ node_labels.stdout_lines }}"
