---
- name: Install required packages for K3s
  apt:
    name:
      - curl
    state: present
    update_cache: true

- name: Download K3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0755'
    validate_certs: false

# 🌟 TASK ĐƯỢC BỔ SUNG: Chạy script cài đặt K3s Server
- name: Execute K3s installation script (Server)
  shell: /tmp/k3s_install.sh
  environment:
    INSTALL_K3S_EXEC: "server --disable traefik --flannel-backend=none --disable-network-policy --cluster-cidr=172.16.0.0/16 --service-cidr=10.43.0.0/16 --tls-san=192.168.58.11 --node-ip=192.168.58.11 --advertise-address=192.168.58.11 --bind-address=192.168.58.11"
  args:
    creates: /var/lib/rancher/k3s/server/node-token

- name: Wait for token to be available
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 120

- name: Read K3s node-token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: token_raw

- name: Set K3s token as fact
  set_fact:
    k3s_token: "{{ token_raw['content'] | b64decode | trim }}"

- name: Enable k3s service
  systemd:
    name: k3s
    enabled: true
    state: started

- name: Allow vagrant user to read kubeconfig
  shell: |
    groupadd -f k3s-readers
    chgrp k3s-readers /etc/rancher/k3s/k3s.yaml
    chmod 640 /etc/rancher/k3s/k3s.yaml
    usermod -aG k3s-readers vagrant
