---
- name: Read kubeconfig from master
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig_raw
  become: true
  run_once: true

- name: Write kubeconfig locally with correct server address
  copy:
    content: "{{ kubeconfig_raw['content'] | b64decode | replace('127.0.0.1', ansible_host) }}"
    dest: "{{ lookup('env', 'PWD') }}/kubeconfig"
    mode: '0600'
  delegate_to: localhost
  become: false
  run_once: true
