---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ctrl-config
  namespace: {{ .Values.global.namespace }}
data:
  controller.json: |
    {
      "server": {
        "port": 8888
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: {{ .Values.global.namespace }}
data:
  gateway.json: |
    {
      "registeredAddr": "gateway-svc:7777",
      "controller": "ctrl-svc:8888",
      "labels": {
      "loc": "{{ .Values.global.gateway.location }}"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsm-config
  namespace: {{ .Values.global.namespace }}
data:
  nsm.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "transportNetworks": ["an1", "an2", "tran1", "tran2"],
      "dataNetworks": [
        {
          "name": "internet",
          "cidr": "10.60.0.0/16",
          "numIpPools": 50
        },
        {
          "name": "etri",
          "cidr": "129.254.195.0/24",
          "dhcpServer": "129.254.195.100"
        }
      ],
      "slices": [
        {
          "id": {"sd": "010203", "sst": 1},
          "dataNetworks": ["internet"]
        },
        {
          "id": {"sd": "543210", "sst": 1},
          "dataNetworks": ["internet"]
        }
      ],
      "amfSets": [
        {
          "setId": "10-100",
          "slices": [{"sd": "010203", "sst": 1}, {"sd": "543210", "sst": 1}]
        },
        {
          "setId": "10-101",
          "slices": [{"sd": "010203", "sst": 1}]
        },
        {
          "setId": "10-102",
          "slices": [{"sd": "010203", "sst": 1}]
        }
      ],
      "udr": {
        "url": "mongodb://udr-mongo:27017",
        "dbName": "etrib5gc",
        "authSub": "authsub",
        "amSub": "amsub",
        "smfSel": "smfSel",
        "smSub": "smSub",
        "mock": false
      },
      "suciProfiles": [
        {
          "protectionScheme": 1,
          "privateKey": "c53c22208b61860b06c62e5406a7b330c2b577aa5558981510d128247d38bd1d",
          "publicKey": "5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650"
        },
        {
          "protectionScheme": 2,
          "privateKey": "F1AB1074477EBCC7F554EA1C5FC368B1616730155E0041AC447D6301975FECDA",
          "publicKey": "0472DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD15A7DED52FCBB097A4ED250E036C7B9C8C7004C4EEDC4F068CD7BF8D3F900E3B4"
        }
      ],
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pran-config
  namespace: {{ .Values.global.namespace }}
data:
  pran.json: |
    {
      "nfSelection": {
        "gnb-loc": "{{ .Values.global.gateway.location }}"
      },
      "nasSplit": false,
      "transportNetworks": ["tran1"],
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "amfRegion": 10,
      "mesh": {
        "registrar": "gateway-svc:7777",
        "labels": {
          "plmnId": "{{ .Values.global.plmn.label }}",
          "tac": "{{ .Values.global.pran.tac }}",
          "app": "pran"
        }
      },
      "ngapBinds": ["{{ .Values.global.pran.ngapBind }}"],
      "ngapPort": {{ .Values.global.pran.ngapPort }}
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-config
  namespace: {{ .Values.global.namespace }}
data:
  udm.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: {{ .Values.global.namespace }}
data:
  ausf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config
  namespace: {{ .Values.global.namespace }}
data:
  pcf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: damf-config
  namespace: {{ .Values.global.namespace }}
data:
  damf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "t3502": 200,
      "t3550": 500,
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-slice1-config
  namespace: {{ .Values.global.namespace }}
data:
  smf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "slice": {
        "sst": 1,
        "sd": "010203"
      },
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-10-100-config
  namespace: {{ .Values.global.namespace }}
data:
  amf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "amfSet": "10-100",
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-10-101-config
  namespace: {{ .Values.global.namespace }}
data:
  amf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "amfSet": "10-101",
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amf-10-102-config
  namespace: {{ .Values.global.namespace }}
data:
  amf.json: |
    {
      "plmnId": {
        "mcc": "{{ .Values.global.plmn.mcc }}",
        "mnc": "{{ .Values.global.plmn.mnc }}"
      },
      "amfSet": "10-102",
      "mesh": {
        "registrar": "gateway-svc:7777"
      }
    }
