---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ctrl-acc
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-svc-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-get-svc-role
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: ctrl-acc
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-svc-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gw-acc
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-pods-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-get-pods-role
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: gw-acc
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-pods-role
