package models

type RegistrationRequest struct {
	PodName      string            `json:"podName"`      //if the agent is in a K8s Pod
	PodNameSpace string            `json:"podNameSpace"` //if the agent is in a K8s Pod
	CertName     string            `json:"certName"`     //agent/NF certificate name for verification
	SbiUrl       string            `json:"sbiUrl"`
	SbiPrefix    string            `json:"sbiPrefix"` //prefix of sbi route paths
	AgentUrl     string            `json:"agentUrl"`
	Labels       map[string]string `json:"labels"` //if K8s mod is off
	Active       bool              `json:"active"` //is sbi server in active state?
	Config       []byte            `json:"config"`
}

type RegistrationFwRequest struct {
	Labels map[string]string `json:"labels"` //if K8s mod is off
	Active bool              `json:"active"` //is sbi server in active state?
	Config []byte            `json:"config"`
}

type RegistrationResponse struct {
	Id   string `json:"id"` //endpoint identity generated by the controller
	GwId string
}

type SubscribeRequest struct {
	Services []string `json:"services"`
}

type SubscribeResponse struct {
	Endpoints map[string]Endpoint //list of relevant endpoints
	Services  map[string]Service  //list of subscibed services
}

type EndpointUpdates struct {
	Left []string   //identities of left endpoints
	Join []Endpoint //list of joined endpoints
}

type UpdateNotification struct {
	InsId  string `json:"insId"`
	Active bool   `json:"active"`
}

type GwRegistrationRequest struct {
	Url    string
	Name   string
	Labels Labels
}

type GwRegistrationResponse struct {
	Id string //uuid generated by controller
}

type ServiceDefinition struct {
	Id string `json:"id"`

	Selectors map[string]string `json:"selectors"`

	Stateful bool `json:"stateful"`
}

type AddServiceRequest []ServiceDefinition
