package sepp

import (
	"fmt"
	//	"github.com/reogac/utils/httpw"
	"net/http"
	"sync"
)

type ServiceInstance interface {
	SendHttpRequest(func(string) (*http.Request, error)) (*http.Response, error)
	GetId() string
}

type LocalEndpoint struct {
	cli  ServiceInstance
	nfId string //1-1 mapping to  a service Id (stateless) or an uuid[gwId] (stateful)
}

type LocalEndpoints struct {
	endpoints         map[string]*LocalEndpoint //index by generated nf id
	instanceIdIndexes map[string]*LocalEndpoint
	mutex             sync.RWMutex
}

func newLocalEndpoints() *LocalEndpoints {
	return &LocalEndpoints{
		endpoints:         make(map[string]*LocalEndpoint),
		instanceIdIndexes: make(map[string]*LocalEndpoint),
	}
}
func (l *LocalEndpoints) getEndpoint(nfId string) *LocalEndpoint {
	l.mutex.RLock()
	defer l.mutex.RUnlock()
	ep, _ := l.endpoints[nfId]
	return ep
}

func (l *LocalEndpoints) findInstance(instanceId string) *LocalEndpoint {
	l.mutex.RLock()
	defer l.mutex.RUnlock()
	ep, _ := l.instanceIdIndexes[instanceId]
	return ep
}

func (l *LocalEndpoints) add(ep *LocalEndpoint) {
	l.mutex.Lock()
	defer l.mutex.Unlock()
	ep.nfId = ep.cli.GetId() //for now just use the instance Id as the nfId
	//TODO: generate nfId
	l.endpoints[ep.nfId] = ep
	l.instanceIdIndexes[ep.cli.GetId()] = ep
}

type RemoteEndpoints struct {
	endpoints   map[string]*RemoteEndpoint //indexed by localId
	nfIdIndexes map[string]*RemoteEndpoint //indexed by SEPP and nfId
	localId     int
	mutex       sync.RWMutex
}

func newRemoteEndpoints() *RemoteEndpoints {
	return &RemoteEndpoints{
		endpoints:   make(map[string]*RemoteEndpoint),
		nfIdIndexes: make(map[string]*RemoteEndpoint),
	}
}

// find remote endpoint from localId
func (l *RemoteEndpoints) getEndpoint(localId string) *RemoteEndpoint {
	l.mutex.RLock()
	defer l.mutex.RUnlock()
	ep, _ := l.endpoints[localId]
	return ep
}

// find with remote Id
func (l *RemoteEndpoints) findByRemoteId(id string) *RemoteEndpoint {
	l.mutex.RLock()
	defer l.mutex.RUnlock()
	ep, _ := l.nfIdIndexes[id]
	return ep
}

// generate localId for a RemoteEndpoint then add it to the list
func (l *RemoteEndpoints) add(ep *RemoteEndpoint) {
	l.mutex.Lock()
	defer l.mutex.Unlock()
	l.localId++
	ep.localId = fmt.Sprintf("remote-endpoint-%d", l.localId)
	l.endpoints[ep.localId] = ep
	l.nfIdIndexes[ep.getRemoteId()] = ep
}

type RemoteEndpoint struct {
	sepp    *SeppPeer //remote SEPP
	nfId    string    //endpoint id generated by a remote SEPP
	localId string    //localId generated for a remote endpoint
}

func (ep *RemoteEndpoint) getRemoteId() string {
	return remoteId(ep.sepp.getId(), ep.nfId)
}

func remoteId(seppId, nfId string) string {
	return fmt.Sprintf("%s:%s", seppId, nfId)
}
