pod_network_cidr: "10.244.0.0/16"

master_ip: "192.168.56.10"
worker1_ip: "192.168.56.11"
worker2_ip: "192.168.56.12"

core_namespace: "etri6g"

gateway_nodeport: 30007
controller_nodeport: 30008
pran_nodeport: 30500
argocd_nodeport: 30080

k3s_version: ""

etri_repo_root: "/vagrant/helm/etrib5gc-main"

dockerfile_path: "/vagrant/docker/nf.Dockerfile"
helm_chart_path: "/vagrant/helm/etrib5gc"
argocd_path: "/vagrant/argocd"

nf_binaries:
  - amf
  - ausf
  - controller
  - damf
  - gateway
  - nsm
  - pcf
  - pran
  - sepp
  - smf
  - udm
  - ue-gen
  - upf

gtp5g_version: "v0.8.2"

upf_binary: "/vagrant/helm/etrib5gc-main/bin/upf"
upf_config_dir: "/etc/b5gc/upf"
upf_service_name: "b5gc-upf"
