package producer

import (
	"etrib5gc/nfs/smf/sm"
	"fmt"
	"github.com/reogac/sbi/models"
	"net/http"
)

func (p *producerImpl) HandleSendMoData(smContextRef string, body *models.SendMoDataRequest) (ersp *models.ExtProblemDetails, prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandlePostPduSessions(body *models.PostPduSessionsRequest) (headers map[string]string, rsp *models.PostPduSessionsResponse, ersp *models.PostPduSessionsErrorResponse, prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandleReleasePduSession(pduSessionRef string, body *models.ReleasePduSessionRequest) (rsp *models.ReleasePduSessionResponse, prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandleRetrievePduSession(pduSessionRef string, body *models.RetrieveData) (rsp *models.RetrievedData, prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandleTransferMoData(pduSessionRef string, body *models.TransferMoDataRequest) (prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandleRetrieveSmContext(smContextRef string, body *models.SmContextRetrieveData) (rsp *models.SmContextRetrievedData, prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandleUpdatePduSession(pduSessionRef string, body *models.UpdatePduSessionRequest) (rsp *models.UpdatePduSessionResponse, ersp *models.UpdatePduSessionErrorResponse, prob *models.ProblemDetails) {
	//TODO: to be implemented
	return
}

func (p *producerImpl) HandleReleaseSmContext(ref string, body *models.ReleaseSmContextRequest) (rsp *models.SmContextReleasedData, prob *models.ProblemDetails) {
	if smCtx := sm.FindSmContext(ref); smCtx == nil {
		p.Errorf("Sm Context not found for %s to handle a ReleaseSmContext request", ref)
		prob = &models.ProblemDetails{
			Status: http.StatusNotFound,
			Detail: fmt.Sprintf("Sm context not found for %s", ref),
		}
	} else {
		info := sm.NewReleaseSmContextContext(body)

		if err := sm.ReceiveSbiEvent[sm.ReleaseSmContextContext](smCtx, sm.SBI_RELEASE_SMCONTEXT, info); err != nil {
			p.Errorf("Failed to handle ReleaseSmContext for %s: %+v", ref, err)
			prob = &models.ProblemDetails{
				Status: http.StatusInternalServerError,
				Detail: "ReleaseSmContext request was not handled",
			}
		} else {
			p.Infof("SmContextReleaseRequest for Sm Context %s was handled", ref)
			rsp = info.Response
		}
	}
	return
}

func (p *producerImpl) HandleUpdateSmContext(ref string, body *models.UpdateSmContextRequest) (rsp *models.UpdateSmContextResponse, ersp *models.UpdateSmContextErrorResponse, prob *models.ProblemDetails) {
	p.Tracef("Receive UpdateSmContext Request")
	if smCtx := sm.FindSmContext(ref); smCtx == nil {
		p.Errorf("Sm Context not found for %s to handle a UpdateSmContext request", ref)
		prob = &models.ProblemDetails{
			Status: http.StatusNotFound,
			Detail: fmt.Sprintf("Sm context not found for %s", ref),
		}
	} else {
		info := sm.NewUpdateSmContextContext(body)
		if err := sm.ReceiveSbiEvent[sm.UpdateSmContextContext](smCtx, sm.SBI_UPDATE_SMCONTEXT, info); err != nil {
			p.Errorf("Failed to handle UpdateSmContext for %s: %+v", ref, err)
			prob = &models.ProblemDetails{
				Status: http.StatusInternalServerError,
				Detail: err.Error(),
			}
		} else {
			rsp, ersp = info.Response, info.ErrResponse
		}
	}
	return
}

func (p *producerImpl) HandlePostSmContexts(callback *models.EndpointInfo, body *models.PostSmContextsRequest) (headers map[string]string, rsp *models.PostSmContextsResponse, ersp *models.PostSmContextsErrorResponse, prob *models.ProblemDetails) {
	supi := body.JsonData.Supi
	sessionId := uint32(*body.JsonData.PduSessionId)

	p.Debugf("Receive PostSmContextRequests for supi=%s, sessionId=%d", supi, sessionId)

	var smCtx *sm.SmContext
	var err error
	if smCtx = sm.FindSmContextBySupi(supi, sessionId); smCtx != nil {
		p.Warnf("Receive a PostSmContext request but SmContext for supi=%s, sessionId=%d exists, release it", supi, sessionId)
		if err := smCtx.ForceRelease(); err != nil { //force release an invalid (orphan) session
			p.Errorf("SmContext [supi=%s, sessionId=%d] was not released: %+v", supi, sessionId, err)
			//fail to release existing session
			ersp = &models.PostSmContextsErrorResponse{
				JsonData: &models.SmContextCreateError{
					Error: models.ExtProblemDetails{
						Status: http.StatusInternalServerError,
						Detail: "Fail to release existing SmContext",
					},
				},
			}
			return
		}
	}

	//A new SmContext will be created with an identity generated by SMF which
	//does not conflict with the released one (if any).
	if smCtx, err = sm.CreateSmContext(*callback, body.JsonData); err != nil {
		p.Errorf("Fail to create a SmContext to handle PostSmContext request: %+v", err)
		ersp = &models.PostSmContextsErrorResponse{
			JsonData: &models.SmContextCreateError{
				Error: models.ExtProblemDetails{
					Status: http.StatusInternalServerError,
					Detail: "Failed to create SmContext",
				},
			},
		}
		return
	}
	p.Infof("A SmContext[supi=%s, sessionId=%d] is created to handle PostSmContextCreate request", supi, sessionId)
	headers, rsp, ersp = smCtx.HandlePostSmContext(body)

	return
}
