package smpc

import (
	"fmt"
	"github.com/reogac/sbi/models"
)

var PolicyTriggers = []models.PolicyControlRequestTrigger{
	models.POLICYCONTROLREQUESTTRIGGER_PLMN_CH,
	models.POLICYCONTROLREQUESTTRIGGER_RES_MO_RE,
	models.POLICYCONTROLREQUESTTRIGGER_AC_TY_CH,
	models.POLICYCONTROLREQUESTTRIGGER_UE_IP_CH,
	models.POLICYCONTROLREQUESTTRIGGER_UE_MAC_CH,
	models.POLICYCONTROLREQUESTTRIGGER_AN_CH_COR,
	models.POLICYCONTROLREQUESTTRIGGER_US_RE,
	models.POLICYCONTROLREQUESTTRIGGER_APP_STA,
	models.POLICYCONTROLREQUESTTRIGGER_APP_STO,
	models.POLICYCONTROLREQUESTTRIGGER_AN_INFO,
	models.POLICYCONTROLREQUESTTRIGGER_CM_SES_FAIL,
	models.POLICYCONTROLREQUESTTRIGGER_PS_DA_OFF,
	models.POLICYCONTROLREQUESTTRIGGER_DEF_QOS_CH,
	models.POLICYCONTROLREQUESTTRIGGER_SE_AMBR_CH,
	models.POLICYCONTROLREQUESTTRIGGER_QOS_NOTIF,
	models.POLICYCONTROLREQUESTTRIGGER_NO_CREDIT,
	models.POLICYCONTROLREQUESTTRIGGER_PRA_CH,
	models.POLICYCONTROLREQUESTTRIGGER_SAREA_CH,
	models.POLICYCONTROLREQUESTTRIGGER_SCNN_CH,
	models.POLICYCONTROLREQUESTTRIGGER_RE_TIMEOUT,
	models.POLICYCONTROLREQUESTTRIGGER_RES_RELEASE,
	models.POLICYCONTROLREQUESTTRIGGER_SUCC_RES_ALLO,
	models.POLICYCONTROLREQUESTTRIGGER_RAT_TY_CH,
	models.POLICYCONTROLREQUESTTRIGGER_REF_QOS_IND_CH,
	models.POLICYCONTROLREQUESTTRIGGER_NUM_OF_PACKET_FILTER,
	models.POLICYCONTROLREQUESTTRIGGER_UE_STATUS_RESUME,
	models.POLICYCONTROLREQUESTTRIGGER_UE_TZ_CH,
}

func BuildPolicyTriggers(bitmap uint64) (triggers []string /*models.PolicyControlRequestTrigger*/) {
	cnt := 0
	size := len(PolicyTriggers)
	for bitmap > 0 && cnt < size {
		if (bitmap & 0x01) > 0 {
			triggers = append(triggers, string(PolicyTriggers[cnt]))
		}
		bitmap >>= 1
		cnt++
	}
	return
}

func sessionId(supi string, pduId uint8) string {
	return fmt.Sprintf("supi=%s,pdu=%d", supi, pduId)
}
